#!/usr/bin/env python3
"""Extract a Lua symbol module from `ie64asm -list` output."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ADDR_LINE = re.compile(r"^\s*([0-9A-Fa-f]{8,16})\s{2,}")
EQU_LINE = re.compile(r"^\s*=\s*([0-9A-Fa-f]{8,16})\s+([A-Za-z_.][A-Za-z0-9_.]*)\b")
LABEL_LINE = re.compile(r"^\s*(?:[A-Za-z][A-Za-z0-9_.]*:\s*)?([A-Za-z_.][A-Za-z0-9_.]*):\s*(?:;.*)?$")
LEA_SYMBOL_LINE = re.compile(
    r"^\s*[0-9A-Fa-f]{8,16}\s+((?:[0-9A-Fa-f]{2}\s+){7}[0-9A-Fa-f]{2})\.\.\.\s+lea\s+\S+,\s*([A-Za-z_.][A-Za-z0-9_.]*)\([^)]*\)"
)
IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_listing(text: str) -> dict[str, int]:
    symbols: dict[str, int] = {}
    pending_labels: list[str] = []
    in_listing = False

    for raw in text.splitlines():
        if raw.strip() == "--- Listing ---":
            in_listing = True
            continue
        if not in_listing:
            continue

        equ = EQU_LINE.match(raw)
        if equ:
            symbols[equ.group(2)] = int(equ.group(1), 16)
            pending_labels.clear()
            continue

        addr = ADDR_LINE.match(raw)
        if addr:
            value = int(addr.group(1), 16)
            for name in pending_labels:
                symbols.setdefault(name, value)
            pending_labels.clear()

        lea = LEA_SYMBOL_LINE.match(raw)
        if lea:
            encoded = bytes(int(b, 16) for b in lea.group(1).split())
            symbols.setdefault(lea.group(2), int.from_bytes(encoded[4:8], "little"))
            continue

        label = LABEL_LINE.match(raw)
        if label:
            pending_labels.append(label.group(1))
        elif raw.strip():
            pending_labels.clear()

    return symbols


def lua_key(name: str) -> str:
    if IDENT.match(name):
        return name
    return "[" + repr(name) + "]"


def emit_lua(symbols: dict[str, int]) -> str:
    lines = [
        "-- Generated by tools/extract_ie64_symbols.py; do not edit.",
        "return {",
    ]
    for name in sorted(symbols):
        lines.append(f"    {lua_key(name)} = 0x{symbols[name]:08X},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("listing", type=Path)
    ap.add_argument("output", type=Path)
    args = ap.parse_args()

    symbols = parse_listing(args.listing.read_text(encoding="utf-8", errors="replace"))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(emit_lua(symbols), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
