package main

const (
	HOST_SOCKET_BASE = AROS_HOST_SOCKET_REGION_BASE

	HOST_SOCKET_CMD     = HOST_SOCKET_BASE + 0x00
	HOST_SOCKET_REQ_PTR = HOST_SOCKET_BASE + 0x04
	HOST_SOCKET_REQ_LEN = HOST_SOCKET_BASE + 0x08
	HOST_SOCKET_RES1    = HOST_SOCKET_BASE + 0x0C
	HOST_SOCKET_RES2    = HOST_SOCKET_BASE + 0x10
	HOST_SOCKET_ERRNO   = HOST_SOCKET_BASE + 0x14
	HOST_SOCKET_HERRNO  = HOST_SOCKET_BASE + 0x18
	HOST_SOCKET_STATUS  = HOST_SOCKET_BASE + 0x1C
	HOST_SOCKET_EVENTS  = HOST_SOCKET_BASE + 0x20

	AROS_HOST_SOCKET_BASE    = HOST_SOCKET_BASE
	AROS_HOST_SOCKET_CMD     = HOST_SOCKET_CMD
	AROS_HOST_SOCKET_REQ_PTR = HOST_SOCKET_REQ_PTR
	AROS_HOST_SOCKET_REQ_LEN = HOST_SOCKET_REQ_LEN
	AROS_HOST_SOCKET_RES1    = HOST_SOCKET_RES1
	AROS_HOST_SOCKET_RES2    = HOST_SOCKET_RES2
	AROS_HOST_SOCKET_ERRNO   = HOST_SOCKET_ERRNO
	AROS_HOST_SOCKET_HERRNO  = HOST_SOCKET_HERRNO
	AROS_HOST_SOCKET_STATUS  = HOST_SOCKET_STATUS
	AROS_HOST_SOCKET_EVENTS  = HOST_SOCKET_EVENTS
)

const (
	HOST_SOCKET_CMD_SOCKET        = 1
	HOST_SOCKET_CMD_BIND          = 2
	HOST_SOCKET_CMD_LISTEN        = 3
	HOST_SOCKET_CMD_ACCEPT        = 4
	HOST_SOCKET_CMD_CONNECT       = 5
	HOST_SOCKET_CMD_SENDTO        = 6
	HOST_SOCKET_CMD_RECVFROM      = 7
	HOST_SOCKET_CMD_SHUTDOWN      = 8
	HOST_SOCKET_CMD_SETSOCKOPT    = 9
	HOST_SOCKET_CMD_GETSOCKOPT    = 10
	HOST_SOCKET_CMD_GETSOCKNAME   = 11
	HOST_SOCKET_CMD_GETPEERNAME   = 12
	HOST_SOCKET_CMD_IOCTL         = 13
	HOST_SOCKET_CMD_CLOSE         = 14
	HOST_SOCKET_CMD_WAITSELECT    = 15
	HOST_SOCKET_CMD_GETHOSTBYNAME = 16
	HOST_SOCKET_CMD_GETHOSTBYADDR = 17
	HOST_SOCKET_CMD_GETHOSTNAME   = 18
	HOST_SOCKET_CMD_DUP2          = 19
	HOST_SOCKET_CMD_GETEVENTS     = 20
	HOST_SOCKET_CMD_RELEASE       = 21
	HOST_SOCKET_CMD_RELEASECOPY   = 22
	HOST_SOCKET_CMD_OBTAIN        = 23

	AROS_HOST_SOCKET_CMD_SOCKET        = HOST_SOCKET_CMD_SOCKET
	AROS_HOST_SOCKET_CMD_BIND          = HOST_SOCKET_CMD_BIND
	AROS_HOST_SOCKET_CMD_LISTEN        = HOST_SOCKET_CMD_LISTEN
	AROS_HOST_SOCKET_CMD_ACCEPT        = HOST_SOCKET_CMD_ACCEPT
	AROS_HOST_SOCKET_CMD_CONNECT       = HOST_SOCKET_CMD_CONNECT
	AROS_HOST_SOCKET_CMD_SENDTO        = HOST_SOCKET_CMD_SENDTO
	AROS_HOST_SOCKET_CMD_RECVFROM      = HOST_SOCKET_CMD_RECVFROM
	AROS_HOST_SOCKET_CMD_SHUTDOWN      = HOST_SOCKET_CMD_SHUTDOWN
	AROS_HOST_SOCKET_CMD_SETSOCKOPT    = HOST_SOCKET_CMD_SETSOCKOPT
	AROS_HOST_SOCKET_CMD_GETSOCKOPT    = HOST_SOCKET_CMD_GETSOCKOPT
	AROS_HOST_SOCKET_CMD_GETSOCKNAME   = HOST_SOCKET_CMD_GETSOCKNAME
	AROS_HOST_SOCKET_CMD_GETPEERNAME   = HOST_SOCKET_CMD_GETPEERNAME
	AROS_HOST_SOCKET_CMD_IOCTL         = HOST_SOCKET_CMD_IOCTL
	AROS_HOST_SOCKET_CMD_CLOSE         = HOST_SOCKET_CMD_CLOSE
	AROS_HOST_SOCKET_CMD_WAITSELECT    = HOST_SOCKET_CMD_WAITSELECT
	AROS_HOST_SOCKET_CMD_GETHOSTBYNAME = HOST_SOCKET_CMD_GETHOSTBYNAME
	AROS_HOST_SOCKET_CMD_GETHOSTBYADDR = HOST_SOCKET_CMD_GETHOSTBYADDR
	AROS_HOST_SOCKET_CMD_GETHOSTNAME   = HOST_SOCKET_CMD_GETHOSTNAME
	AROS_HOST_SOCKET_CMD_DUP2          = HOST_SOCKET_CMD_DUP2
	AROS_HOST_SOCKET_CMD_GETEVENTS     = HOST_SOCKET_CMD_GETEVENTS
	AROS_HOST_SOCKET_CMD_RELEASE       = HOST_SOCKET_CMD_RELEASE
	AROS_HOST_SOCKET_CMD_RELEASECOPY   = HOST_SOCKET_CMD_RELEASECOPY
	AROS_HOST_SOCKET_CMD_OBTAIN        = HOST_SOCKET_CMD_OBTAIN
)

const (
	HOST_SOCKET_REQ_WORDS = arosHostSocketReqWords
	HOST_SOCKET_REQ_SIZE  = arosHostSocketReqSize
	HOST_SOCKET_MAX_IO    = arosHostSocketMaxIO
	HOST_SOCKET_MAX_ADDR  = arosHostSocketMaxAddr
	HOST_SOCKET_DTABLE    = arosHostSocketDTable
	HOST_SOCKET_FDSET_LEN = arosHostSocketFDSetLen
)

const (
	arosHostSocketStatusReady = 0
	arosHostSocketStatusBusy  = 1
	arosHostSocketStatusError = 2
)

const (
	arosHostSocketReqWords = 24
	arosHostSocketReqSize  = arosHostSocketReqWords * 4
	arosHostSocketMaxIO    = 64 * 1024
	arosHostSocketMaxAddr  = 128
	arosHostSocketDTable   = 64
	arosHostSocketFDSetLen = 8
)

const (
	arosSockErrNone       = 0
	arosSockErrBadf       = 9
	arosSockErrInval      = 22
	arosSockErrMsgSize    = 40
	arosSockErrOpNotSupp  = 45
	arosSockErrNoBufs     = 55
	arosSockErrNoSys      = 78
	arosSockErrWouldBlock = 35
	arosSockHHostNotFound = 1
	arosSockHNoRecovery   = 3
)

type arosHostSocketTimeval struct {
	Sec  int32
	Usec int32
}
