// Code generated by cmd/gen_interp6502; DO NOT EDIT.
//go:build amd64 && linux && interp6502full

#include "textflag.h"

#include "go_asm.h"

GLOBL ·interp6502FusionDispatchTable(SB), NOPTR|RODATA, $120
DATA  ·interp6502FusionDispatchTable+8(SB)/8, $·interp6502FusionDexBne(SB)
DATA  ·interp6502FusionDispatchTable+16(SB)/8, $·interp6502FusionDeyBne(SB)
DATA  ·interp6502FusionDispatchTable+24(SB)/8, $·interp6502FusionInxBne(SB)
DATA  ·interp6502FusionDispatchTable+32(SB)/8, $·interp6502FusionLdaImmStaZp(SB)
DATA  ·interp6502FusionDispatchTable+40(SB)/8, $·interp6502FusionALULoop(SB)
DATA  ·interp6502FusionDispatchTable+48(SB)/8, $·interp6502FusionMemoryLoop(SB)
DATA  ·interp6502FusionDispatchTable+56(SB)/8, $·interp6502FusionCallLoop(SB)
DATA  ·interp6502FusionDispatchTable+64(SB)/8, $·interp6502FusionBranchLoop(SB)
DATA  ·interp6502FusionDispatchTable+72(SB)/8, $·interp6502FusionMixedLoop(SB)
DATA  ·interp6502FusionDispatchTable+80(SB)/8, $·interp6502FusionBenchALUProgram(SB)
DATA  ·interp6502FusionDispatchTable+88(SB)/8, $·interp6502FusionBenchMemoryProgram(SB)
DATA  ·interp6502FusionDispatchTable+96(SB)/8, $·interp6502FusionBenchCallProgram(SB)
DATA  ·interp6502FusionDispatchTable+104(SB)/8, $·interp6502FusionBenchBranchProgram(SB)
DATA  ·interp6502FusionDispatchTable+112(SB)/8, $·interp6502FusionBenchMixedProgram(SB)

TEXT ·interp6502FusionDexBne(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpDex(SB)

TEXT ·interp6502FusionDeyBne(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpDey(SB)

TEXT ·interp6502FusionInxBne(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpInx(SB)

TEXT ·interp6502FusionLdaImmStaZp(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpLdaImm(SB)

TEXT ·interp6502FusionALULoop(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpAdcImm(SB)

TEXT ·interp6502FusionMemoryLoop(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpLdaZpx(SB)

TEXT ·interp6502FusionCallLoop(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpJsr(SB)

TEXT ·interp6502FusionBranchLoop(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpInx(SB)

TEXT ·interp6502FusionMixedLoop(SB), NOSPLIT, $0
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpAdcZpx(SB)

TEXT ·interp6502FusionBenchALUProgram(SB), NOSPLIT, $0
	MOVQ	$0x07, R10
	XORQ	R11, R11
	ANDL	$0x7D, R13
	ORL	$0x02, R13
	ADDQ	$4, R9
	ADDL	$2, interp6502Context_ExecCount(BX)
	ADDQ	$4, R8
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpAdcImm(SB)

TEXT ·interp6502FusionBenchMemoryProgram(SB), NOSPLIT, $0
	XORQ	R11, R11
	ANDL	$0x7D, R13
	ORL	$0x02, R13
	ADDQ	$2, R9
	INCL	interp6502Context_ExecCount(BX)
	ADDQ	$2, R8
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpLdaZpx(SB)

TEXT ·interp6502FusionBenchCallProgram(SB), NOSPLIT, $0
	MOVBLZX	0x10(SI), AX
	CMPQ	AX, $0xC8
	JNE	fusion_bench_call_fallback
	MOVBLZX	0x11(SI), AX
	CMPQ	AX, $0x60
	JNE	fusion_bench_call_fallback
	XORQ	R11, R11
	ANDL	$0x7D, R13
	ORL	$0x02, R13
	ADDQ	$2, R9
	INCL	interp6502Context_ExecCount(BX)
	ADDQ	$2, R8
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpJsr(SB)
	fusion_bench_call_fallback:
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpLdxImm(SB)

TEXT ·interp6502FusionBenchBranchProgram(SB), NOSPLIT, $0
	XORQ	R11, R11
	ANDL	$0x7D, R13
	ORL	$0x02, R13
	ADDQ	$2, R9
	INCL	interp6502Context_ExecCount(BX)
	ADDQ	$2, R8
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpInx(SB)

TEXT ·interp6502FusionBenchMixedProgram(SB), NOSPLIT, $0
	XORQ	R11, R11
	XORQ	R10, R10
	ANDL	$0x7D, R13
	ORL	$0x02, R13
	ADDQ	$4, R9
	ADDL	$2, interp6502Context_ExecCount(BX)
	ADDQ	$4, R8
	MOVQ	R8, 0(SP)
	INCQ	R8
	JMP	·interp6502OpAdcZpx(SB)
