package main

import _ "embed"

// embeddedRuntimeBlob is the standalone COMPILE runtime blob. It is embedded into the
// host binary unconditionally (NOT gated on embed_basic): COMPILE needs it whenever the
// guest compiles an expression/variable/string/control-flow programme, and -basic runs
// without embed_basic too (a custom -basic-image or the prebuilt fallback). The File I/O
// device serves these bytes for the reserved virtual filename runtimeBlobFileName, so
// COMPILE bundles the blob into standalone .ie64 images without the user placing a
// sidecar file in their working directory.
//
// The blob is committed (a .gitignore exception) and regenerated by the aot-runtime-blob
// make target (tools/gen_runtime_blob) before the host is built. TestAOTRuntimeBlob
// guards that it matches a fresh assemble + trim of the runtime sources, so the embedded
// bytes cannot drift. go:embed requires the file at build time; it is always present in a
// checkout, so a plain `go build` (with or without embed_basic) embeds the current blob.
//
//go:embed sdk/include/aot_runtime_blob.bin
var embeddedRuntimeBlob []byte

func init() {
	compiledFeatures = append(compiledFeatures, "basic:runtime-blob")
}
