package main

const (
	IE_SFX_REGION_BASE = 0xF0E80
	IE_SFX_REGION_END  = 0xF0EFF

	IE_SFX_EXT_REGION_BASE = 0xF2600
	IE_SFX_EXT_REGION_END  = 0xF29FF

	IE_SFX_LEGACY_CHANNELS = 4
	IE_SFX_CH_BASE         = IE_SFX_REGION_BASE
	IE_SFX_CH_STRIDE       = 0x20
	IE_SFX_CHANNELS        = 32

	IE_SFX_EXT_CH_BASE = IE_SFX_EXT_REGION_BASE

	IE_SFX_8BIT_EXT_BANK       = IE_SFX_EXT_REGION_BASE / 0x2000
	IE_SFX_8BIT_EXT_CH_BASE    = 0x2000 + (IE_SFX_EXT_REGION_BASE % 0x2000)
	IE_SFX_8BIT_EXT_REGION_END = IE_SFX_8BIT_EXT_CH_BASE + (IE_SFX_EXT_REGION_END - IE_SFX_EXT_REGION_BASE)

	SFX_PTR          = 0x00
	SFX_LEN          = 0x04
	SFX_LOOP_PTR     = 0x08
	SFX_LOOP_LEN     = 0x0C
	SFX_FREQ         = 0x10
	SFX_VOL          = 0x14
	SFX_PAN_RESERVED = 0x16
	SFX_FORMAT       = 0x18
	SFX_CTRL         = 0x1C

	SFX_FORMAT_SIGNED8   = 0
	SFX_FORMAT_UNSIGNED8 = 1
	SFX_FORMAT_SIGNED16  = 2

	SFX_CTRL_TRIGGER = 1 << 0
	SFX_CTRL_STOP    = 1 << 1
	SFX_CTRL_LOOP_EN = 1 << 2

	SFX_STATUS_PLAYING = 1 << 0
	SFX_STATUS_ERROR   = 1 << 1
)
