package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type caseKind string

const (
	kindInt caseKind = "int"
	kindFPU caseKind = "fpu"
)

type regExpect struct {
	Reg   string // e.g. "d0", "a0"
	Value uint32
}

type testCase struct {
	ID          string
	Shard       string
	Kind        caseKind
	Name        string
	Input       string
	Expected    string
	Setup       []string
	Body        []string
	ActualMode  string // regsr, regonly, fp64, custom_*, mem32, multi_reg, exception, fpsr_only
	ExpectReg   string
	ExpectValue uint32
	SRMask      uint16
	ExpectSR    uint16
	ExpectHi    uint32
	ExpectLo    uint32
	FPSRMask    uint32
	ExpectFPSR  uint32
	// Phase 1 new fields
	ExpectMemAddr uint32
	ExpectMemVal  uint32
	ExpectRegs    []regExpect
	ExpectSP      uint32
	StackVals     []uint32
	ExpectTrap    bool
	TrapVector    int
	DataPool      []string // raw asm lines emitted after the case
}

type shard struct {
	Name  string
	Title string
	Cases []testCase
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

func main() {
	root, err := os.Getwd()
	if err != nil {
		fail(err)
	}
	outDir := filepath.Join(root, "sdk", "cputest", "generated")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fail(err)
	}

	shards := buildCatalog()
	totalCases := 0
	for _, shard := range shards {
		totalCases += len(shard.Cases)
		path := filepath.Join(outDir, shard.Name+"_cases.inc")
		if err := os.WriteFile(path, []byte(renderShard(shard)), 0o644); err != nil {
			fail(err)
		}
	}
	manifestPath := filepath.Join(root, "sdk", "cputest", "include", "cputest_manifest.inc")
	if err := os.MkdirAll(filepath.Dir(manifestPath), 0o755); err != nil {
		fail(err)
	}
	if err := os.WriteFile(manifestPath, []byte(renderManifest(shards, totalCases)), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("Generated %d shards, %d cases total\n", len(shards), totalCases)
}

// ---------------------------------------------------------------------------
// Catalog assembly
// ---------------------------------------------------------------------------

func buildCatalog() []shard {
	var shards []shard
	shards = append(shards, buildExistingShards()...)
	shards = append(shards, buildPhase2Shards()...)
	shards = append(shards, buildPhase3Shards()...)
	shards = append(shards, buildPhase4Shards()...)
	shards = append(shards, buildPhase5Shards()...)
	shards = append(shards, buildPhase6Shards()...)
	shards = append(shards, buildPhase7Shards()...)
	shards = append(shards, buildPhase8Shards()...)
	slices.SortFunc(shards, func(a, b shard) int {
		return strings.Compare(a.Name, b.Name)
	})
	return shards
}

// ---------------------------------------------------------------------------
// Manifest renderer
// ---------------------------------------------------------------------------

func renderManifest(shards []shard, totalCases int) string {
	var buf bytes.Buffer
	buf.WriteString("; Code generated by cmd/gen_m68k_cputest. DO NOT EDIT.\n\n")
	buf.WriteString("ct_suite_shards:\n")
	for _, shard := range shards {
		fmt.Fprintf(&buf, "                dc.l    run_%s_shard\n", shard.Name)
	}
	buf.WriteString("                dc.l    0\n")
	fmt.Fprintf(&buf, "\n; Expected total case count for verification\n")
	fmt.Fprintf(&buf, "ct_set_expected_total:\n")
	fmt.Fprintf(&buf, "                move.l  #%d,ct_expected_total\n", totalCases)
	fmt.Fprintf(&buf, "                rts\n")
	return buf.String()
}

// ---------------------------------------------------------------------------
// Shard renderer
// ---------------------------------------------------------------------------

func renderShard(sh shard) string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "; Code generated by cmd/gen_m68k_cputest. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "; Shard: %s\n\n", sh.Name)
	fmt.Fprintf(&buf, "run_%s_shard:\n", sh.Name)
	fmt.Fprintf(&buf, "                lea     ct_shard_name_%s(pc),a0\n", sh.Name)
	buf.WriteString("                jsr     ct_enter_shard\n")
	for _, tc := range sh.Cases {
		fmt.Fprintf(&buf, "                bsr     case_%s\n", tc.ID)
	}
	buf.WriteString("                rts\n\n")
	fmt.Fprintf(&buf, "ct_shard_name_%s:\n", sh.Name)
	fmt.Fprintf(&buf, "                dc.b    \"%s\",0\n", sh.Title)
	buf.WriteString("                even\n\n")

	for _, tc := range sh.Cases {
		renderCase(&buf, tc)
	}
	return buf.String()
}

// ---------------------------------------------------------------------------
// Case renderer
// ---------------------------------------------------------------------------

func renderCase(buf *bytes.Buffer, tc testCase) {
	fmt.Fprintf(buf, "case_%s:\n", tc.ID)
	for _, line := range tc.Setup {
		fmt.Fprintf(buf, "                %s\n", line)
	}
	for _, line := range tc.Body {
		fmt.Fprintf(buf, "                %s\n", line)
	}
	switch tc.Kind {
	case kindInt:
		renderIntCheck(buf, tc)
	case kindFPU:
		renderFPUCheck(buf, tc)
	}
	buf.WriteString(".name:\n")
	fmt.Fprintf(buf, "                dc.b    \"%s\",0\n", asmString(tc.Name))
	buf.WriteString(".input:\n")
	fmt.Fprintf(buf, "                dc.b    \"%s\",0\n", asmString(tc.Input))
	buf.WriteString(".expected:\n")
	fmt.Fprintf(buf, "                dc.b    \"%s\",0\n", asmString(tc.Expected))
	buf.WriteString("                even\n")
	for _, line := range tc.DataPool {
		fmt.Fprintf(buf, "%s\n", line)
	}
	buf.WriteString("\n")
}

func renderIntCheck(buf *bytes.Buffer, tc testCase) {
	switch tc.ActualMode {
	case "custom_d1_sr":
		buf.WriteString("                move.l  d1,d0\n")
		buf.WriteString("                move.w  sr,d1\n")
		fmt.Fprintf(buf, "                andi.w  #$%04X,d1\n", tc.SRMask)
		fmt.Fprintf(buf, "                cmp.l   #$%08X,d0\n", tc.ExpectValue)
		buf.WriteString("                bne.s   .fail\n")
		fmt.Fprintf(buf, "                cmpi.w  #$%04X,d1\n", tc.ExpectSR)
		buf.WriteString("                bne.s   .fail\n")
	case "custom_a0_only":
		buf.WriteString("                move.l  a0,d0\n")
		fmt.Fprintf(buf, "                cmp.l   #$%08X,d0\n", tc.ExpectValue)
		buf.WriteString("                bne.s   .fail\n")
	case "custom_a2_only":
		buf.WriteString("                move.l  a2,d0\n")
		fmt.Fprintf(buf, "                cmp.l   #$%08X,d0\n", tc.ExpectValue)
		buf.WriteString("                bne.s   .fail\n")
	case "custom_sp_mem":
		buf.WriteString("                move.l  sp,d0\n")
		fmt.Fprintf(buf, "                cmp.l   #$%08X,d0\n", tc.ExpectSP)
		buf.WriteString("                bne.s   .fail\n")
		buf.WriteString("                move.l  (sp),d0\n")
		fmt.Fprintf(buf, "                cmp.l   #$%08X,d0\n", tc.ExpectMemVal)
		buf.WriteString("                bne.s   .fail\n")
	case "custom_sr_only":
		buf.WriteString("                move.w  sr,d1\n")
		fmt.Fprintf(buf, "                andi.w  #$%04X,d1\n", tc.SRMask)
		fmt.Fprintf(buf, "                cmpi.w  #$%04X,d1\n", tc.ExpectSR)
		buf.WriteString("                bne.s   .fail\n")
	case "mem32":
		fmt.Fprintf(buf, "                move.l  $%08X,d0\n", tc.ExpectMemAddr)
		fmt.Fprintf(buf, "                cmp.l   #$%08X,d0\n", tc.ExpectMemVal)
		buf.WriteString("                bne.s   .fail\n")
	case "multi_reg":
		for i, re := range tc.ExpectRegs {
			if i == 0 {
				fmt.Fprintf(buf, "                move.l  %s,d0\n", re.Reg)
				fmt.Fprintf(buf, "                cmp.l   #$%08X,d0\n", re.Value)
				buf.WriteString("                bne.s   .fail\n")
			} else {
				fmt.Fprintf(buf, "                move.l  %s,d1\n", re.Reg)
				fmt.Fprintf(buf, "                cmp.l   #$%08X,d1\n", re.Value)
				buf.WriteString("                bne.s   .fail\n")
			}
		}
	case "exception":
		buf.WriteString("                jsr     ct_restore_trap_handler\n")
		buf.WriteString("                jsr     ct_check_trap_taken\n")
		if tc.ExpectTrap {
			buf.WriteString("                tst.l   d0\n")
			buf.WriteString("                beq.s   .fail\n")
			fmt.Fprintf(buf, "                cmpi.l  #%d,ct_trap_vector\n", tc.TrapVector)
			buf.WriteString("                bne.s   .fail\n")
		} else {
			buf.WriteString("                tst.l   d0\n")
			buf.WriteString("                bne.s   .fail\n")
		}
	case "fpsr_only":
		buf.WriteString("                fmove.l fpsr,d0\n")
		fmt.Fprintf(buf, "                andi.l  #$%08X,d0\n", tc.FPSRMask)
		fmt.Fprintf(buf, "                cmpi.l  #$%08X,d0\n", tc.ExpectFPSR)
		buf.WriteString("                bne.s   .fail\n")
	default: // "regsr", "regonly"
		fmt.Fprintf(buf, "                move.l  %s,d0\n", strings.ToUpper(tc.ExpectReg))
		buf.WriteString("                move.w  sr,d1\n")
		fmt.Fprintf(buf, "                andi.w  #$%04X,d1\n", tc.SRMask)
		fmt.Fprintf(buf, "                cmp.l   #$%08X,d0\n", tc.ExpectValue)
		buf.WriteString("                bne.s   .fail\n")
		if tc.SRMask != 0 {
			fmt.Fprintf(buf, "                cmpi.w  #$%04X,d1\n", tc.ExpectSR)
			buf.WriteString("                bne.s   .fail\n")
		}
	}
	buf.WriteString("                lea     .name(pc),a0\n")
	buf.WriteString("                jsr     ct_log_pass\n")
	buf.WriteString("                rts\n")
	buf.WriteString(".fail:\n")
	buf.WriteString("                lea     .name(pc),a0\n")
	buf.WriteString("                lea     .input(pc),a1\n")
	buf.WriteString("                lea     .expected(pc),a2\n")
	switch tc.ActualMode {
	case "mem32":
		buf.WriteString("                jsr     ct_fail_mem32\n")
	case "multi_reg":
		buf.WriteString("                jsr     ct_fail_multi_reg\n")
	case "exception":
		buf.WriteString("                move.l  ct_trap_taken,d0\n")
		buf.WriteString("                move.l  ct_trap_vector,d1\n")
		buf.WriteString("                jsr     ct_fail_exception\n")
	case "regonly", "custom_a0_only", "custom_a2_only":
		buf.WriteString("                jsr     ct_fail_reg_only\n")
	default:
		buf.WriteString("                jsr     ct_fail_reg_sr\n")
	}
}

func renderFPUCheck(buf *bytes.Buffer, tc testCase) {
	buf.WriteString("                fmove.l fpsr,ct_fpsr_shadow\n")
	buf.WriteString("                fmove.d fp0,ct_fp_scratch\n")
	buf.WriteString("                move.l  ct_fp_scratch,d0\n")
	buf.WriteString("                move.l  ct_fp_scratch+4,d1\n")
	buf.WriteString("                move.l  ct_fpsr_shadow,d2\n")
	fmt.Fprintf(buf, "                andi.l  #$%08X,d2\n", tc.FPSRMask)
	fmt.Fprintf(buf, "                cmpi.l  #$%08X,d0\n", tc.ExpectHi)
	buf.WriteString("                bne.s   .fail\n")
	fmt.Fprintf(buf, "                cmpi.l  #$%08X,d1\n", tc.ExpectLo)
	buf.WriteString("                bne.s   .fail\n")
	fmt.Fprintf(buf, "                cmpi.l  #$%08X,d2\n", tc.ExpectFPSR)
	buf.WriteString("                bne.s   .fail\n")
	buf.WriteString("                lea     .name(pc),a0\n")
	buf.WriteString("                jsr     ct_log_pass\n")
	buf.WriteString("                rts\n")
	buf.WriteString(".fail:\n")
	buf.WriteString("                lea     .name(pc),a0\n")
	buf.WriteString("                lea     .input(pc),a1\n")
	buf.WriteString("                lea     .expected(pc),a2\n")
	buf.WriteString("                jsr     ct_fail_fp64\n")
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

func asmString(s string) string {
	return strings.ReplaceAll(s, "\"", "'")
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

// intCase is a helper for constructing integer test cases with common defaults.
func intCase(shard, id, name, input, expected, mode, reg string, val uint32, srMask, expectSR uint16, setup, body []string, pool ...string) testCase {
	return testCase{
		ID:          id,
		Shard:       shard,
		Kind:        kindInt,
		Name:        name,
		Input:       input,
		Expected:    expected,
		ActualMode:  mode,
		ExpectReg:   reg,
		ExpectValue: val,
		SRMask:      srMask,
		ExpectSR:    expectSR,
		Setup:       setup,
		Body:        body,
		DataPool:    pool,
	}
}

// fpuCase is a helper for FPU cases.
func fpuCase(shard, id, name, input, expected string, hi, lo, fpsrMask, expectFPSR uint32, setup, body []string, pool ...string) testCase {
	return testCase{
		ID:         id,
		Shard:      shard,
		Kind:       kindFPU,
		Name:       name,
		Input:      input,
		Expected:   expected,
		ActualMode: "fp64",
		ExpectHi:   hi,
		ExpectLo:   lo,
		FPSRMask:   fpsrMask,
		ExpectFPSR: expectFPSR,
		Setup:      setup,
		Body:       body,
		DataPool:   pool,
	}
}

func regsr(shard, id, name, input, expected, reg string, val uint32, srMask, expectSR uint16, setup, body []string, pool ...string) testCase {
	return intCase(shard, id, name, input, expected, "regsr", reg, val, srMask, expectSR, setup, body, pool...)
}

func regonly(shard, id, name, input, expected, reg string, val uint32, setup, body []string, pool ...string) testCase {
	return intCase(shard, id, name, input, expected, "regonly", reg, val, 0, 0, setup, body, pool...)
}
