package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"sort"

	"github.com/intuitionamiga/IntuitionEngine/internal/interp6502meta"
)

func main() {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		fail(fmt.Errorf("runtime.Caller failed"))
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", ".."))

	if err := os.WriteFile(filepath.Join(root, "cpu_6502_interp_meta_generated.go"), mustGenGo(), 0o644); err != nil {
		fail(err)
	}
	if err := os.WriteFile(filepath.Join(root, "cpu_6502_interp_dispatch_table_generated_amd64.s"), mustGenAsm(), 0o644); err != nil {
		fail(err)
	}
	if err := os.WriteFile(filepath.Join(root, "cpu_6502_interp_fusion_dispatch_generated_amd64.s"), mustGenFusionAsm(), 0o644); err != nil {
		fail(err)
	}
}

func mustGenGo() []byte {
	var lengths [256]byte
	for _, op := range interp6502meta.Opcodes {
		lengths[op.Opcode] = op.Length
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen_interp6502; DO NOT EDIT.\n")
	buf.WriteString("package main\n\n")
	buf.WriteString("var interp6502OpcodeLenTable = [256]byte{\n")
	for i, n := range lengths {
		if n == 0 {
			continue
		}
		fmt.Fprintf(&buf, "\t0x%02X: %d,\n", i, n)
	}
	buf.WriteString("}\n")
	buf.WriteString("\n")
	buf.WriteString("const (\n")
	buf.WriteString("\tinterp6502FusionNone byte = iota\n")
	for _, fusion := range interp6502meta.Fusions {
		fmt.Fprintf(&buf, "\tinterp6502Fusion%s\n", fusion.Name)
	}
	buf.WriteString(")\n\n")
	buf.WriteString("type interp6502FusionMeta struct {\n")
	buf.WriteString("\tid    byte\n")
	buf.WriteString("\tname  string\n")
	buf.WriteString("\tbytes []byte\n")
	buf.WriteString("\thandler string\n")
	buf.WriteString("}\n\n")
	buf.WriteString("var interp6502FusionTable = []interp6502FusionMeta{\n")
	for _, fusion := range interp6502meta.Fusions {
		fmt.Fprintf(&buf, "\t{id: interp6502Fusion%s, name: %q, bytes: []byte{", fusion.Name, fusion.Name)
		for i, b := range fusion.Bytes {
			if i > 0 {
				buf.WriteString(", ")
			}
			fmt.Fprintf(&buf, "0x%02X", b)
		}
		fmt.Fprintf(&buf, "}, handler: %q},\n", fusion.HandlerName)
	}
	buf.WriteString("}\n")

	out, err := format.Source(buf.Bytes())
	if err != nil {
		fail(err)
	}
	return out
}

func mustGenAsm() []byte {
	ops := append([]interp6502meta.OpcodeMeta(nil), interp6502meta.Opcodes...)
	sort.Slice(ops, func(i, j int) bool { return ops[i].Opcode < ops[j].Opcode })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen_interp6502; DO NOT EDIT.\n")
	buf.WriteString("//go:build amd64 && linux\n\n")
	buf.WriteString("#include \"textflag.h\"\n\n")
	buf.WriteString("GLOBL ·interp6502DispatchTable(SB), NOPTR|RODATA, $2048\n")
	for _, op := range ops {
		fmt.Fprintf(&buf, "DATA  ·interp6502DispatchTable+%d(SB)/8, $·%s(SB)\n", int(op.Opcode)*8, op.HandlerName)
	}
	return buf.Bytes()
}

func mustGenFusionAsm() []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/gen_interp6502; DO NOT EDIT.\n")
	buf.WriteString("//go:build amd64 && linux\n\n")
	buf.WriteString("#include \"textflag.h\"\n\n")
	buf.WriteString("#include \"go_asm.h\"\n\n")
	size := (len(interp6502meta.Fusions) + 1) * 8
	fmt.Fprintf(&buf, "GLOBL ·interp6502FusionDispatchTable(SB), NOPTR|RODATA, $%d\n", size)
	for i, fusion := range interp6502meta.Fusions {
		fmt.Fprintf(&buf, "DATA  ·interp6502FusionDispatchTable+%d(SB)/8, $·%s(SB)\n", (i+1)*8, fusion.HandlerName)
	}
	buf.WriteString("\n")
	for _, fusion := range interp6502meta.Fusions {
		fmt.Fprintf(&buf, "TEXT ·%s(SB), NOSPLIT, $0\n", fusion.HandlerName)
		for _, line := range fusion.Body {
			buf.WriteString("\t")
			buf.WriteString(line)
			buf.WriteString("\n")
		}
		buf.WriteString("\n")
	}
	return buf.Bytes()
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
