// regen_symbols scans script_engine.go for the Lua module surface and
// writes the canonical symbol list to stdout (or to a file via -o).
//
// It looks for blocks of the form:
//
//	VAR := L.SetFuncs(L.NewTable(), map[string]lua.LGFunction{
//	    "name":   se.luaFn(),
//	    ...
//	})
//
// followed (in the enclosing function) by:
//
//	L.SetGlobal("MODULE", VAR)
//
// Output is one "module.name" per line, sorted, with a comment header.
//
// Run from the repo root:
//
//	go run ./tools/prm-extract/cmd/regen_symbols > tools/prm-extract/symbols.txt

package main

import (
	"bufio"
	"flag"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
)

var (
	setFuncsRe = regexp.MustCompile(`^\s*(\w+)\s*:=\s*L\.SetFuncs\(L\.NewTable\(\),\s*map\[string\]lua\.LGFunction\{\s*$`)
	keyRe      = regexp.MustCompile(`^\s*"([a-zA-Z_][a-zA-Z0-9_]*)"\s*:`)
	setGlobalRe = regexp.MustCompile(`^\s*L\.SetGlobal\("([a-zA-Z_][a-zA-Z0-9_]*)"\s*,\s*(\w+)\)\s*$`)
	mapEndRe    = regexp.MustCompile(`^\s*\}\)\s*$`)
)

func main() {
	in := flag.String("in", "script_engine.go", "path to script_engine.go")
	out := flag.String("o", "", "output file (default stdout)")
	flag.Parse()

	syms, err := scan(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, "regen_symbols:", err)
		os.Exit(1)
	}
	var sink io.Writer = os.Stdout
	if *out != "" {
		f, err := os.Create(*out)
		if err != nil {
			fmt.Fprintln(os.Stderr, "regen_symbols:", err)
			os.Exit(1)
		}
		defer f.Close()
		sink = f
	}
	w := bufio.NewWriter(sink)
	defer w.Flush()
	fmt.Fprintf(w, "# Auto-generated by tools/prm-extract/cmd/regen_symbols.\n")
	fmt.Fprintf(w, "# Run: go run ./tools/prm-extract/cmd/regen_symbols -o tools/prm-extract/symbols.txt\n")
	fmt.Fprintf(w, "# Each line is a Lua call target the IES lint accepts.\n")
	for _, s := range syms {
		fmt.Fprintln(w, s)
	}
}

func scan(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	// First pass: collect varname → []funcname maps and varname → moduleName.
	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 1024*1024), 16*1024*1024)

	type group struct {
		varName string
		keys    []string
	}
	var (
		groups       []*group
		current      *group
		varToModule  = map[string]string{}
		varToGroup   = map[string]*group{}
	)

	for scanner.Scan() {
		line := scanner.Text()
		if current == nil {
			if m := setFuncsRe.FindStringSubmatch(line); m != nil {
				current = &group{varName: m[1]}
				groups = append(groups, current)
				varToGroup[m[1]] = current
				continue
			}
			if m := setGlobalRe.FindStringSubmatch(line); m != nil {
				varToModule[m[2]] = m[1]
			}
			continue
		}
		if mapEndRe.MatchString(line) {
			current = nil
			continue
		}
		if m := keyRe.FindStringSubmatch(line); m != nil {
			current.keys = append(current.keys, m[1])
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}

	var out []string
	for _, g := range groups {
		mod, ok := varToModule[g.varName]
		if !ok {
			continue
		}
		for _, k := range g.keys {
			out = append(out, mod+"."+k)
		}
	}
	sort.Strings(out)
	// Dedup just in case (e.g. if a module is set up twice).
	uniq := out[:0]
	for i, s := range out {
		if i == 0 || s != out[i-1] {
			uniq = append(uniq, s)
		}
	}
	return uniq, nil
}

// ensure strings import is used even after regex trims
var _ = strings.TrimSpace
