package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/intuitionamiga/IntuitionEngine/internal/ie64meta"
)

type target struct {
	path  string
	build string
	body  func(*bytes.Buffer)
}

func main() {
	out := flag.String("out", ".", "output root")
	flag.Parse()

	root, err := filepath.Abs(*out)
	if err != nil {
		fatalf("resolve output root: %v", err)
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		if os.IsNotExist(err) {
			if mkErr := os.MkdirAll(root, 0755); mkErr != nil {
				fatalf("create output root: %v", mkErr)
			}
			root, err = filepath.EvalSymlinks(root)
		}
		if err != nil {
			fatalf("canonicalise output root: %v", err)
		}
	}

	for _, t := range targets() {
		data := render(t)
		dst, err := safeJoin(root, t.path)
		if err != nil {
			fatalf("%s: %v", t.path, err)
		}
		if err := os.MkdirAll(filepath.Dir(dst), 0755); err != nil {
			fatalf("create %s parent: %v", t.path, err)
		}
		if err := os.WriteFile(dst, data, 0644); err != nil {
			fatalf("write %s: %v", t.path, err)
		}
	}
}

func targets() []target {
	return []target{
		{path: "cpu_ie64_opcodes_gen.go", body: cpuOpcodes},
		{path: "assembler/ie64asm_opcodes_gen.go", build: "ie64", body: publicAssemblerOpcodes},
		{path: "internal/asm/ie64/opcodes_gen.go", body: internalAssemblerOpcodes},
		{path: "debug_disasm_ie64_opcodes_gen.go", body: debugDisassemblerOpcodes},
		{path: "assembler/ie64dis_opcodes_gen.go", build: "ie64dis", body: standaloneDisassemblerOpcodes},
	}
}

func render(t target) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by go run ./cmd/gen_ie64_opmeta; DO NOT EDIT.\n")
	if t.build != "" {
		fmt.Fprintf(&b, "\n//go:build %s\n", t.build)
	}
	b.WriteByte('\n')
	switch {
	case strings.HasPrefix(t.path, "internal/asm/ie64/"):
		b.WriteString("package ie64\n\n")
	default:
		b.WriteString("package main\n\n")
	}
	t.body(&b)
	data, err := format.Source(b.Bytes())
	if err != nil {
		fatalf("format %s: %v\n%s", t.path, err, b.String())
	}
	return data
}

func cpuOpcodes(b *bytes.Buffer) {
	b.WriteString("const (\n")
	for _, row := range ie64meta.Rows {
		fmt.Fprintf(b, "\t%s = 0x%02X\n", row.CPUName, row.Opcode)
	}
	b.WriteString(")\n")
}

func publicAssemblerOpcodes(b *bytes.Buffer) {
	b.WriteString("const (\n")
	for _, row := range ie64meta.Rows {
		fmt.Fprintf(b, "\t%s = 0x%02X\n", row.PublicAssemblerName, row.Opcode)
	}
	b.WriteString(")\n")
}

func internalAssemblerOpcodes(b *bytes.Buffer) {
	b.WriteString("const (\n")
	for _, row := range ie64meta.Rows {
		fmt.Fprintf(b, "\t%s = 0x%02X\n", row.InternalAssemblerName, row.Opcode)
	}
	b.WriteString(")\n")
}

func debugDisassemblerOpcodes(b *bytes.Buffer) {
	b.WriteString("var ie64OpcodeNames = map[byte]string{\n")
	for _, row := range ie64meta.Rows {
		fmt.Fprintf(b, "\t%s: %q,\n", row.DebugDisassemblerName, row.CanonicalMnemonic)
	}
	b.WriteString("}\n")
}

func standaloneDisassemblerOpcodes(b *bytes.Buffer) {
	b.WriteString("const (\n")
	for _, row := range ie64meta.Rows {
		fmt.Fprintf(b, "\t%s = 0x%02X\n", row.StandaloneDisName, row.Opcode)
	}
	b.WriteString(")\n\n")
	b.WriteString("var opcodeNames = map[byte]string{\n")
	for _, row := range ie64meta.Rows {
		fmt.Fprintf(b, "\t%s: %q,\n", row.StandaloneDisName, row.CanonicalMnemonic)
	}
	b.WriteString("}\n")
}

func safeJoin(root, rel string) (string, error) {
	if filepath.IsAbs(rel) || filepath.Clean(rel) != rel {
		return "", fmt.Errorf("unsafe generated path %q", rel)
	}
	dst := filepath.Join(root, rel)
	cleanRoot := filepath.Clean(root)
	cleanDst := filepath.Clean(dst)
	if cleanDst != cleanRoot && !strings.HasPrefix(cleanDst, cleanRoot+string(os.PathSeparator)) {
		return "", fmt.Errorf("generated path escapes output root")
	}
	return cleanDst, nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
