// Code generated by go run ./cmd/gen_ie64_opmeta; DO NOT EDIT.

//go:build ie64dis

package main

const (
	dis64_MOVE     = 0x01
	dis64_MOVT     = 0x02
	dis64_MOVEQ    = 0x03
	dis64_LEA      = 0x04
	dis64_LOAD     = 0x10
	dis64_STORE    = 0x11
	dis64_ADD      = 0x20
	dis64_SUB      = 0x21
	dis64_MULU     = 0x22
	dis64_MULS     = 0x23
	dis64_DIVU     = 0x24
	dis64_DIVS     = 0x25
	dis64_MOD      = 0x26
	dis64_NEG      = 0x27
	dis64_MODS     = 0x28
	dis64_MULHU    = 0x29
	dis64_MULHS    = 0x2A
	dis64_AND      = 0x30
	dis64_OR       = 0x31
	dis64_EOR      = 0x32
	dis64_NOT      = 0x33
	dis64_LSL      = 0x34
	dis64_LSR      = 0x35
	dis64_ASR      = 0x36
	dis64_CLZ      = 0x37
	dis64_SEXT     = 0x38
	dis64_ROL      = 0x39
	dis64_ROR      = 0x3A
	dis64_CTZ      = 0x3B
	dis64_POPCNT   = 0x3C
	dis64_BSWAP    = 0x3D
	dis64_BRA      = 0x40
	dis64_BEQ      = 0x41
	dis64_BNE      = 0x42
	dis64_BLT      = 0x43
	dis64_BGE      = 0x44
	dis64_BGT      = 0x45
	dis64_BLE      = 0x46
	dis64_BHI      = 0x47
	dis64_BLS      = 0x48
	dis64_JMP      = 0x49
	dis64_JSR      = 0x50
	dis64_RTS      = 0x51
	dis64_PUSH     = 0x52
	dis64_POP      = 0x53
	dis64_JSRI     = 0x54
	dis64_FMOV     = 0x60
	dis64_FLOAD    = 0x61
	dis64_FSTORE   = 0x62
	dis64_FADD     = 0x63
	dis64_FSUB     = 0x64
	dis64_FMUL     = 0x65
	dis64_FDIV     = 0x66
	dis64_FMOD     = 0x67
	dis64_FABS     = 0x68
	dis64_FNEG     = 0x69
	dis64_FSQRT    = 0x6A
	dis64_FINT     = 0x6B
	dis64_FCMP     = 0x6C
	dis64_FCVTIF   = 0x6D
	dis64_FCVTFI   = 0x6E
	dis64_FMOVI    = 0x6F
	dis64_FMOVO    = 0x70
	dis64_FSIN     = 0x71
	dis64_FCOS     = 0x72
	dis64_FTAN     = 0x73
	dis64_FATAN    = 0x74
	dis64_FLOG     = 0x75
	dis64_FEXP     = 0x76
	dis64_FPOW     = 0x77
	dis64_FMOVECR  = 0x78
	dis64_FMOVSR   = 0x79
	dis64_FMOVCR   = 0x7A
	dis64_FMOVSC   = 0x7B
	dis64_FMOVCC   = 0x7C
	dis64_DMOV     = 0x80
	dis64_DLOAD    = 0x81
	dis64_DSTORE   = 0x82
	dis64_DADD     = 0x83
	dis64_DSUB     = 0x84
	dis64_DMUL     = 0x85
	dis64_DDIV     = 0x86
	dis64_DMOD     = 0x87
	dis64_DABS     = 0x88
	dis64_DNEG     = 0x89
	dis64_DSQRT    = 0x8A
	dis64_DINT     = 0x8B
	dis64_DCMP     = 0x8C
	dis64_DCVTIF   = 0x8D
	dis64_DCVTFI   = 0x8E
	dis64_FCVTSD   = 0x8F
	dis64_FCVTDS   = 0x90
	dis64_DSIN     = 0x91
	dis64_DCOS     = 0x92
	dis64_DTAN     = 0x93
	dis64_DATAN    = 0x94
	dis64_DLOG     = 0x95
	dis64_DEXP     = 0x96
	dis64_DPOW     = 0x97
	dis64_NOP      = 0xE0
	dis64_HALT     = 0xE1
	dis64_SEI      = 0xE2
	dis64_CLI      = 0xE3
	dis64_RTI      = 0xE4
	dis64_WAIT     = 0xE5
	dis64_MTCR     = 0xE6
	dis64_MFCR     = 0xE7
	dis64_ERET     = 0xE8
	dis64_TLBFLUSH = 0xE9
	dis64_TLBINVAL = 0xEA
	dis64_SYSCALL  = 0xEB
	dis64_SMODE    = 0xEC
	dis64_CAS      = 0xED
	dis64_XCHG     = 0xEE
	dis64_FAA      = 0xEF
	dis64_FAND     = 0xF0
	dis64_FOR      = 0xF1
	dis64_FXOR     = 0xF2
	dis64_SUAEN    = 0xF3
	dis64_SUADIS   = 0xF4
)

var opcodeNames = map[byte]string{
	dis64_MOVE:     "move",
	dis64_MOVT:     "movt",
	dis64_MOVEQ:    "moveq",
	dis64_LEA:      "lea",
	dis64_LOAD:     "load",
	dis64_STORE:    "store",
	dis64_ADD:      "add",
	dis64_SUB:      "sub",
	dis64_MULU:     "mulu",
	dis64_MULS:     "muls",
	dis64_DIVU:     "divu",
	dis64_DIVS:     "divs",
	dis64_MOD:      "mod",
	dis64_NEG:      "neg",
	dis64_MODS:     "mods",
	dis64_MULHU:    "mulhu",
	dis64_MULHS:    "mulhs",
	dis64_AND:      "and",
	dis64_OR:       "or",
	dis64_EOR:      "eor",
	dis64_NOT:      "not",
	dis64_LSL:      "lsl",
	dis64_LSR:      "lsr",
	dis64_ASR:      "asr",
	dis64_CLZ:      "clz",
	dis64_SEXT:     "sext",
	dis64_ROL:      "rol",
	dis64_ROR:      "ror",
	dis64_CTZ:      "ctz",
	dis64_POPCNT:   "popcnt",
	dis64_BSWAP:    "bswap",
	dis64_BRA:      "bra",
	dis64_BEQ:      "beq",
	dis64_BNE:      "bne",
	dis64_BLT:      "blt",
	dis64_BGE:      "bge",
	dis64_BGT:      "bgt",
	dis64_BLE:      "ble",
	dis64_BHI:      "bhi",
	dis64_BLS:      "bls",
	dis64_JMP:      "jmp",
	dis64_JSR:      "jsr",
	dis64_RTS:      "rts",
	dis64_PUSH:     "push",
	dis64_POP:      "pop",
	dis64_JSRI:     "jsr",
	dis64_FMOV:     "fmov",
	dis64_FLOAD:    "fload",
	dis64_FSTORE:   "fstore",
	dis64_FADD:     "fadd",
	dis64_FSUB:     "fsub",
	dis64_FMUL:     "fmul",
	dis64_FDIV:     "fdiv",
	dis64_FMOD:     "fmod",
	dis64_FABS:     "fabs",
	dis64_FNEG:     "fneg",
	dis64_FSQRT:    "fsqrt",
	dis64_FINT:     "fint",
	dis64_FCMP:     "fcmp",
	dis64_FCVTIF:   "fcvtif",
	dis64_FCVTFI:   "fcvtfi",
	dis64_FMOVI:    "fmovi",
	dis64_FMOVO:    "fmovo",
	dis64_FSIN:     "fsin",
	dis64_FCOS:     "fcos",
	dis64_FTAN:     "ftan",
	dis64_FATAN:    "fatan",
	dis64_FLOG:     "flog",
	dis64_FEXP:     "fexp",
	dis64_FPOW:     "fpow",
	dis64_FMOVECR:  "fmovecr",
	dis64_FMOVSR:   "fmovsr",
	dis64_FMOVCR:   "fmovcr",
	dis64_FMOVSC:   "fmovsc",
	dis64_FMOVCC:   "fmovcc",
	dis64_DMOV:     "dmov",
	dis64_DLOAD:    "dload",
	dis64_DSTORE:   "dstore",
	dis64_DADD:     "dadd",
	dis64_DSUB:     "dsub",
	dis64_DMUL:     "dmul",
	dis64_DDIV:     "ddiv",
	dis64_DMOD:     "dmod",
	dis64_DABS:     "dabs",
	dis64_DNEG:     "dneg",
	dis64_DSQRT:    "dsqrt",
	dis64_DINT:     "dint",
	dis64_DCMP:     "dcmp",
	dis64_DCVTIF:   "dcvtif",
	dis64_DCVTFI:   "dcvtfi",
	dis64_FCVTSD:   "fcvtsd",
	dis64_FCVTDS:   "fcvtds",
	dis64_DSIN:     "dsin",
	dis64_DCOS:     "dcos",
	dis64_DTAN:     "dtan",
	dis64_DATAN:    "datan",
	dis64_DLOG:     "dlog",
	dis64_DEXP:     "dexp",
	dis64_DPOW:     "dpow",
	dis64_NOP:      "nop",
	dis64_HALT:     "halt",
	dis64_SEI:      "sei",
	dis64_CLI:      "cli",
	dis64_RTI:      "rti",
	dis64_WAIT:     "wait",
	dis64_MTCR:     "mtcr",
	dis64_MFCR:     "mfcr",
	dis64_ERET:     "eret",
	dis64_TLBFLUSH: "tlbflush",
	dis64_TLBINVAL: "tlbinval",
	dis64_SYSCALL:  "syscall",
	dis64_SMODE:    "smode",
	dis64_CAS:      "cas",
	dis64_XCHG:     "xchg",
	dis64_FAA:      "faa",
	dis64_FAND:     "fand",
	dis64_FOR:      "for",
	dis64_FXOR:     "fxor",
	dis64_SUAEN:    "suaen",
	dis64_SUADIS:   "suadis",
}
