package ie64meta

// Row describes one architecturally known IE64 opcode. This package is plain
// typed data only so generators and tests can import it without pulling in the
// emulator, assembler, or disassembler packages.
type Row struct {
	Opcode                 byte
	CPUName                string
	PublicAssemblerName    string
	InternalAssemblerName  string
	DebugDisassemblerName  string
	StandaloneDisName      string
	CanonicalMnemonic      string
	FormatClass            string
	Assemblable            bool
	PublicAssemblerForms   []string
	InternalAssemblerForms []string
	PublicOrigin           uint64
	InternalOrigin         uint64
}

// Rows is the single source for IE64 opcode values, generated names, canonical
// mnemonics, broad formatting classes, and one-line assembler coverage forms.
var Rows = []Row{
	row(0x01, "OP_MOVE", "OP64_MOVE", "opMove", "OP_MOVE", "dis64_MOVE", "move", "move", "move.l r1, #$1234"),
	row(0x02, "OP_MOVT", "OP64_MOVT", "opMovt", "OP_MOVT", "dis64_MOVT", "movt", "imm-reg", "movt r1, #$1234"),
	row(0x03, "OP_MOVEQ", "OP64_MOVEQ", "opMoveq", "OP_MOVEQ", "dis64_MOVEQ", "moveq", "imm-reg", "moveq r1, #$1234"),
	row(0x04, "OP_LEA", "OP64_LEA", "opLea", "OP_LEA", "dis64_LEA", "lea", "mem-addr", "lea r1, 4(r2)"),
	row(0x10, "OP_LOAD", "OP64_LOAD", "opLoad", "OP_LOAD", "dis64_LOAD", "load", "mem-load", "load.l r1, 4(r2)"),
	row(0x11, "OP_STORE", "OP64_STORE", "opStore", "OP_STORE", "dis64_STORE", "store", "mem-store", "store.l r1, 4(r2)"),
	row(0x20, "OP_ADD", "OP64_ADD", "opAdd", "OP_ADD", "dis64_ADD", "add", "alu3", "add.l r1, r2, r3"),
	row(0x21, "OP_SUB", "OP64_SUB", "opSub", "OP_SUB", "dis64_SUB", "sub", "alu3", "sub.l r1, r2, r3"),
	row(0x22, "OP_MULU", "OP64_MULU", "opMulu", "OP_MULU", "dis64_MULU", "mulu", "alu3", "mulu.l r1, r2, r3"),
	row(0x23, "OP_MULS", "OP64_MULS", "opMuls", "OP_MULS", "dis64_MULS", "muls", "alu3", "muls.l r1, r2, r3"),
	row(0x24, "OP_DIVU", "OP64_DIVU", "opDivu", "OP_DIVU", "dis64_DIVU", "divu", "alu3", "divu.l r1, r2, r3"),
	row(0x25, "OP_DIVS", "OP64_DIVS", "opDivs", "OP_DIVS", "dis64_DIVS", "divs", "alu3", "divs.l r1, r2, r3"),
	row(0x26, "OP_MOD64", "OP64_MOD", "opMod", "OP_MOD64", "dis64_MOD", "mod", "alu3", "mod.l r1, r2, r3"),
	row(0x27, "OP_NEG", "OP64_NEG", "opNeg", "OP_NEG", "dis64_NEG", "neg", "alu2", "neg.l r1, r2"),
	row(0x28, "OP_MODS", "OP64_MODS", "opMods", "OP_MODS", "dis64_MODS", "mods", "alu3", "mods.l r1, r2, r3"),
	row(0x29, "OP_MULHU", "OP64_MULHU", "opMulhu", "OP_MULHU", "dis64_MULHU", "mulhu", "alu3-q", "mulhu r1, r2, r3"),
	row(0x2A, "OP_MULHS", "OP64_MULHS", "opMulhs", "OP_MULHS", "dis64_MULHS", "mulhs", "alu3-q", "mulhs r1, r2, r3"),
	row(0x30, "OP_AND64", "OP64_AND", "opAnd", "OP_AND64", "dis64_AND", "and", "alu3", "and.l r1, r2, r3"),
	row(0x31, "OP_OR64", "OP64_OR", "opOr", "OP_OR64", "dis64_OR", "or", "alu3", "or.l r1, r2, r3"),
	row(0x32, "OP_EOR", "OP64_EOR", "opEor", "OP_EOR", "dis64_EOR", "eor", "alu3", "eor.l r1, r2, r3"),
	row(0x33, "OP_NOT64", "OP64_NOT", "opNot", "OP_NOT64", "dis64_NOT", "not", "alu2", "not.l r1, r2"),
	row(0x34, "OP_LSL", "OP64_LSL", "opLsl", "OP_LSL", "dis64_LSL", "lsl", "alu3", "lsl.l r1, r2, r3"),
	row(0x35, "OP_LSR", "OP64_LSR", "opLsr", "OP_LSR", "dis64_LSR", "lsr", "alu3", "lsr.l r1, r2, r3"),
	row(0x36, "OP_ASR", "OP64_ASR", "opAsr", "OP_ASR", "dis64_ASR", "asr", "alu3", "asr.l r1, r2, r3"),
	row(0x37, "OP_CLZ", "OP64_CLZ", "opClz", "OP_CLZ", "dis64_CLZ", "clz", "alu2-l", "clz.l r1, r2"),
	row(0x38, "OP_SEXT", "OP64_SEXT", "opSext", "OP_SEXT", "dis64_SEXT", "sext", "alu2", "sext.l r1, r2"),
	row(0x39, "OP_ROL", "OP64_ROL", "opRol", "OP_ROL", "dis64_ROL", "rol", "alu3", "rol.l r1, r2, r3"),
	row(0x3A, "OP_ROR", "OP64_ROR", "opRor", "OP_ROR", "dis64_ROR", "ror", "alu3", "ror.l r1, r2, r3"),
	row(0x3B, "OP_CTZ", "OP64_CTZ", "opCtz", "OP_CTZ", "dis64_CTZ", "ctz", "alu2-l", "ctz.l r1, r2"),
	row(0x3C, "OP_POPCNT", "OP64_POPCNT", "opPopcnt", "OP_POPCNT", "dis64_POPCNT", "popcnt", "alu2-l", "popcnt.l r1, r2"),
	row(0x3D, "OP_BSWAP", "OP64_BSWAP", "opBswap", "OP_BSWAP", "dis64_BSWAP", "bswap", "alu2-l", "bswap.l r1, r2"),
	row(0x40, "OP_BRA", "OP64_BRA", "opBra", "OP_BRA", "dis64_BRA", "bra", "branch", "bra $1010"),
	row(0x41, "OP_BEQ", "OP64_BEQ", "opBeq", "OP_BEQ", "dis64_BEQ", "beq", "branch-cond", "beq r1, r2, $1010"),
	row(0x42, "OP_BNE", "OP64_BNE", "opBne", "OP_BNE", "dis64_BNE", "bne", "branch-cond", "bne r1, r2, $1010"),
	row(0x43, "OP_BLT", "OP64_BLT", "opBlt", "OP_BLT", "dis64_BLT", "blt", "branch-cond", "blt r1, r2, $1010"),
	row(0x44, "OP_BGE", "OP64_BGE", "opBge", "OP_BGE", "dis64_BGE", "bge", "branch-cond", "bge r1, r2, $1010"),
	row(0x45, "OP_BGT", "OP64_BGT", "opBgt", "OP_BGT", "dis64_BGT", "bgt", "branch-cond", "bgt r1, r2, $1010"),
	row(0x46, "OP_BLE", "OP64_BLE", "opBle", "OP_BLE", "dis64_BLE", "ble", "branch-cond", "ble r1, r2, $1010"),
	row(0x47, "OP_BHI", "OP64_BHI", "opBhi", "OP_BHI", "dis64_BHI", "bhi", "branch-cond", "bhi r1, r2, $1010"),
	row(0x48, "OP_BLS", "OP64_BLS", "opBls", "OP_BLS", "dis64_BLS", "bls", "branch-cond", "bls r1, r2, $1010"),
	row(0x49, "OP_JMP", "OP64_JMP", "opJmp", "OP_JMP", "dis64_JMP", "jmp", "jump-indirect", "jmp 4(r2)"),
	row(0x50, "OP_JSR64", "OP64_JSR", "opJsr", "OP_JSR64", "dis64_JSR", "jsr", "call", "jsr $1010"),
	row(0x51, "OP_RTS64", "OP64_RTS", "opRts", "OP_RTS64", "dis64_RTS", "rts", "no-operand", "rts"),
	row(0x52, "OP_PUSH64", "OP64_PUSH", "opPush", "OP_PUSH64", "dis64_PUSH", "push", "stack", "push r1"),
	row(0x53, "OP_POP64", "OP64_POP", "opPop", "OP_POP64", "dis64_POP", "pop", "stack", "pop r1"),
	row(0x54, "OP_JSR_IND", "OP64_JSR_IND", "opJsrInd", "OP_JSR_IND", "dis64_JSRI", "jsr", "call-indirect", "jsr 4(r2)"),
	row(0x60, "OP_FMOV", "OP64_FMOV", "opFmov", "OP_FMOV", "dis64_FMOV", "fmov", "fp2", "fmov f1, f2"),
	row(0x61, "OP_FLOAD", "OP64_FLOAD", "opFload", "OP_FLOAD", "dis64_FLOAD", "fload", "fp-mem", "fload f1, 4(r2)"),
	row(0x62, "OP_FSTORE", "OP64_FSTORE", "opFstore", "OP_FSTORE", "dis64_FSTORE", "fstore", "fp-mem", "fstore f1, 4(r2)"),
	row(0x63, "OP_FADD", "OP64_FADD", "opFadd", "OP_FADD", "dis64_FADD", "fadd", "fp3", "fadd f1, f2, f3"),
	row(0x64, "OP_FSUB", "OP64_FSUB", "opFsub", "OP_FSUB", "dis64_FSUB", "fsub", "fp3", "fsub f1, f2, f3"),
	row(0x65, "OP_FMUL", "OP64_FMUL", "opFmul", "OP_FMUL", "dis64_FMUL", "fmul", "fp3", "fmul f1, f2, f3"),
	row(0x66, "OP_FDIV", "OP64_FDIV", "opFdiv", "OP_FDIV", "dis64_FDIV", "fdiv", "fp3", "fdiv f1, f2, f3"),
	row(0x67, "OP_FMOD", "OP64_FMOD", "opFmod", "OP_FMOD", "dis64_FMOD", "fmod", "fp3", "fmod f1, f2, f3"),
	row(0x68, "OP_FABS", "OP64_FABS", "opFabs", "OP_FABS", "dis64_FABS", "fabs", "fp2", "fabs f1, f2"),
	row(0x69, "OP_FNEG", "OP64_FNEG", "opFneg", "OP_FNEG", "dis64_FNEG", "fneg", "fp2", "fneg f1, f2"),
	row(0x6A, "OP_FSQRT", "OP64_FSQRT", "opFsqrt", "OP_FSQRT", "dis64_FSQRT", "fsqrt", "fp2", "fsqrt f1, f2"),
	row(0x6B, "OP_FINT", "OP64_FINT", "opFint", "OP_FINT", "dis64_FINT", "fint", "fp2", "fint f1, f2"),
	row(0x6C, "OP_FCMP", "OP64_FCMP", "opFcmp", "OP_FCMP", "dis64_FCMP", "fcmp", "fp3-int", "fcmp r1, f2, f3"),
	row(0x6D, "OP_FCVTIF", "OP64_FCVTIF", "opFcvtif", "OP_FCVTIF", "dis64_FCVTIF", "fcvtif", "fp-gpr", "fcvtif f1, r2"),
	row(0x6E, "OP_FCVTFI", "OP64_FCVTFI", "opFcvtfi", "OP_FCVTFI", "dis64_FCVTFI", "fcvtfi", "fp-gpr", "fcvtfi r1, f2"),
	row(0x6F, "OP_FMOVI", "OP64_FMOVI", "opFmovi", "OP_FMOVI", "dis64_FMOVI", "fmovi", "fp-gpr", "fmovi f1, r2"),
	row(0x70, "OP_FMOVO", "OP64_FMOVO", "opFmovo", "OP_FMOVO", "dis64_FMOVO", "fmovo", "fp-gpr", "fmovo r1, f2"),
	row(0x71, "OP_FSIN", "OP64_FSIN", "opFsin", "OP_FSIN", "dis64_FSIN", "fsin", "fp2", "fsin f1, f2"),
	row(0x72, "OP_FCOS", "OP64_FCOS", "opFcos", "OP_FCOS", "dis64_FCOS", "fcos", "fp2", "fcos f1, f2"),
	row(0x73, "OP_FTAN", "OP64_FTAN", "opFtan", "OP_FTAN", "dis64_FTAN", "ftan", "fp2", "ftan f1, f2"),
	row(0x74, "OP_FATAN", "OP64_FATAN", "opFatan", "OP_FATAN", "dis64_FATAN", "fatan", "fp2", "fatan f1, f2"),
	row(0x75, "OP_FLOG", "OP64_FLOG", "opFlog", "OP_FLOG", "dis64_FLOG", "flog", "fp2", "flog f1, f2"),
	row(0x76, "OP_FEXP", "OP64_FEXP", "opFexp", "OP_FEXP", "dis64_FEXP", "fexp", "fp2", "fexp f1, f2"),
	row(0x77, "OP_FPOW", "OP64_FPOW", "opFpow", "OP_FPOW", "dis64_FPOW", "fpow", "fp3", "fpow f1, f2, f3"),
	row(0x78, "OP_FMOVECR", "OP64_FMOVECR", "opFmovecr", "OP_FMOVECR", "dis64_FMOVECR", "fmovecr", "fp-imm", "fmovecr f1, #5"),
	row(0x79, "OP_FMOVSR", "OP64_FMOVSR", "opFmovsr", "OP_FMOVSR", "dis64_FMOVSR", "fmovsr", "fp-status", "fmovsr r1"),
	row(0x7A, "OP_FMOVCR", "OP64_FMOVCR", "opFmovcr", "OP_FMOVCR", "dis64_FMOVCR", "fmovcr", "fp-status", "fmovcr r1"),
	row(0x7B, "OP_FMOVSC", "OP64_FMOVSC", "opFmovsc", "OP_FMOVSC", "dis64_FMOVSC", "fmovsc", "fp-status", "fmovsc r1"),
	row(0x7C, "OP_FMOVCC", "OP64_FMOVCC", "opFmovcc", "OP_FMOVCC", "dis64_FMOVCC", "fmovcc", "fp-status", "fmovcc r1"),
	row(0x80, "OP_DMOV", "OP64_DMOV", "opDmov", "OP_DMOV", "dis64_DMOV", "dmov", "fp2-even", "dmov f0, f2"),
	row(0x81, "OP_DLOAD", "OP64_DLOAD", "opDload", "OP_DLOAD", "dis64_DLOAD", "dload", "fp-mem-even", "dload f0, 4(r2)"),
	row(0x82, "OP_DSTORE", "OP64_DSTORE", "opDstore", "OP_DSTORE", "dis64_DSTORE", "dstore", "fp-mem-even", "dstore f0, 4(r2)"),
	row(0x83, "OP_DADD", "OP64_DADD", "opDadd", "OP_DADD", "dis64_DADD", "dadd", "fp3-even", "dadd f0, f2, f4"),
	row(0x84, "OP_DSUB", "OP64_DSUB", "opDsub", "OP_DSUB", "dis64_DSUB", "dsub", "fp3-even", "dsub f0, f2, f4"),
	row(0x85, "OP_DMUL", "OP64_DMUL", "opDmul", "OP_DMUL", "dis64_DMUL", "dmul", "fp3-even", "dmul f0, f2, f4"),
	row(0x86, "OP_DDIV", "OP64_DDIV", "opDdiv", "OP_DDIV", "dis64_DDIV", "ddiv", "fp3-even", "ddiv f0, f2, f4"),
	row(0x87, "OP_DMOD", "OP64_DMOD", "opDmod", "OP_DMOD", "dis64_DMOD", "dmod", "fp3-even", "dmod f0, f2, f4"),
	row(0x88, "OP_DABS", "OP64_DABS", "opDabs", "OP_DABS", "dis64_DABS", "dabs", "fp2-even", "dabs f0, f2"),
	row(0x89, "OP_DNEG", "OP64_DNEG", "opDneg", "OP_DNEG", "dis64_DNEG", "dneg", "fp2-even", "dneg f0, f2"),
	row(0x8A, "OP_DSQRT", "OP64_DSQRT", "opDsqrt", "OP_DSQRT", "dis64_DSQRT", "dsqrt", "fp2-even", "dsqrt f0, f2"),
	row(0x8B, "OP_DINT", "OP64_DINT", "opDint", "OP_DINT", "dis64_DINT", "dint", "fp2-even", "dint f0, f2"),
	row(0x8C, "OP_DCMP", "OP64_DCMP", "opDcmp", "OP_DCMP", "dis64_DCMP", "dcmp", "fp3-int-even", "dcmp r1, f2, f4"),
	row(0x8D, "OP_DCVTIF", "OP64_DCVTIF", "opDcvtif", "OP_DCVTIF", "dis64_DCVTIF", "dcvtif", "fp-gpr-even", "dcvtif f0, r2"),
	row(0x8E, "OP_DCVTFI", "OP64_DCVTFI", "opDcvtfi", "OP_DCVTFI", "dis64_DCVTFI", "dcvtfi", "fp-gpr-even", "dcvtfi r1, f2"),
	row(0x8F, "OP_FCVTSD", "OP64_FCVTSD", "opFcvtsd", "OP_FCVTSD", "dis64_FCVTSD", "fcvtsd", "fp-convert", "fcvtsd f0, f1"),
	row(0x90, "OP_FCVTDS", "OP64_FCVTDS", "opFcvtds", "OP_FCVTDS", "dis64_FCVTDS", "fcvtds", "fp-convert", "fcvtds f1, f0"),
	row(0x91, "OP_DSIN", "OP64_DSIN", "opDsin", "OP_DSIN", "dis64_DSIN", "dsin", "fp2-even", "dsin f0, f2"),
	row(0x92, "OP_DCOS", "OP64_DCOS", "opDcos", "OP_DCOS", "dis64_DCOS", "dcos", "fp2-even", "dcos f0, f2"),
	row(0x93, "OP_DTAN", "OP64_DTAN", "opDtan", "OP_DTAN", "dis64_DTAN", "dtan", "fp2-even", "dtan f0, f2"),
	row(0x94, "OP_DATAN", "OP64_DATAN", "opDatan", "OP_DATAN", "dis64_DATAN", "datan", "fp2-even", "datan f0, f2"),
	row(0x95, "OP_DLOG", "OP64_DLOG", "opDlog", "OP_DLOG", "dis64_DLOG", "dlog", "fp2-even", "dlog f0, f2"),
	row(0x96, "OP_DEXP", "OP64_DEXP", "opDexp", "OP_DEXP", "dis64_DEXP", "dexp", "fp2-even", "dexp f0, f2"),
	row(0x97, "OP_DPOW", "OP64_DPOW", "opDpow", "OP_DPOW", "dis64_DPOW", "dpow", "fp3-even", "dpow f0, f2, f4"),
	row(0xE0, "OP_NOP64", "OP64_NOP", "opNop", "OP_NOP64", "dis64_NOP", "nop", "no-operand", "nop"),
	row(0xE1, "OP_HALT64", "OP64_HALT", "opHalt", "OP_HALT64", "dis64_HALT", "halt", "no-operand", "halt"),
	row(0xE2, "OP_SEI64", "OP64_SEI", "opSei", "OP_SEI64", "dis64_SEI", "sei", "no-operand", "sei"),
	row(0xE3, "OP_CLI64", "OP64_CLI", "opCli", "OP_CLI64", "dis64_CLI", "cli", "no-operand", "cli"),
	row(0xE4, "OP_RTI64", "OP64_RTI", "opRti", "OP_RTI64", "dis64_RTI", "rti", "no-operand", "rti"),
	row(0xE5, "OP_WAIT64", "OP64_WAIT", "opWait", "OP_WAIT64", "dis64_WAIT", "wait", "imm", "wait #5"),
	row(0xE6, "OP_MTCR", "OP64_MTCR", "opMtcr", "OP_MTCR", "dis64_MTCR", "mtcr", "control", "mtcr cr1, r2"),
	row(0xE7, "OP_MFCR", "OP64_MFCR", "opMfcr", "OP_MFCR", "dis64_MFCR", "mfcr", "control", "mfcr r1, cr2"),
	row(0xE8, "OP_ERET", "OP64_ERET", "opEret", "OP_ERET", "dis64_ERET", "eret", "no-operand", "eret"),
	row(0xE9, "OP_TLBFLUSH", "OP64_TLBFLUSH", "opTlbflush", "OP_TLBFLUSH", "dis64_TLBFLUSH", "tlbflush", "no-operand", "tlbflush"),
	row(0xEA, "OP_TLBINVAL", "OP64_TLBINVAL", "opTlbinval", "OP_TLBINVAL", "dis64_TLBINVAL", "tlbinval", "control", "tlbinval r2"),
	row(0xEB, "OP_SYSCALL", "OP64_SYSCALL", "opSyscall", "OP_SYSCALL", "dis64_SYSCALL", "syscall", "imm", "syscall #5"),
	row(0xEC, "OP_SMODE", "OP64_SMODE", "opSmode", "OP_SMODE", "dis64_SMODE", "smode", "control", "smode r1"),
	row(0xED, "OP_CAS", "OP64_CAS", "opCas", "OP_CAS", "dis64_CAS", "cas", "atomic", "cas r1, 4(r2), r3"),
	row(0xEE, "OP_XCHG", "OP64_XCHG", "opXchg", "OP_XCHG", "dis64_XCHG", "xchg", "atomic", "xchg r1, 4(r2), r3"),
	row(0xEF, "OP_FAA", "OP64_FAA", "opFaa", "OP_FAA", "dis64_FAA", "faa", "atomic", "faa r1, 4(r2), r3"),
	row(0xF0, "OP_FAND", "OP64_FAND", "opFand", "OP_FAND", "dis64_FAND", "fand", "atomic", "fand r1, 4(r2), r3"),
	row(0xF1, "OP_FOR", "OP64_FOR", "opFor", "OP_FOR", "dis64_FOR", "for", "atomic", "for r1, 4(r2), r3"),
	row(0xF2, "OP_FXOR", "OP64_FXOR", "opFxor", "OP_FXOR", "dis64_FXOR", "fxor", "atomic", "fxor r1, 4(r2), r3"),
	row(0xF3, "OP_SUAEN", "OP64_SUAEN", "opSuaen", "OP_SUAEN", "dis64_SUAEN", "suaen", "no-operand", "suaen"),
	row(0xF4, "OP_SUADIS", "OP64_SUADIS", "opSuadis", "OP_SUADIS", "dis64_SUADIS", "suadis", "no-operand", "suadis"),
}

func row(opcode byte, cpuName, publicName, internalName, debugName, standaloneName, mnemonic, format, form string) Row {
	return Row{
		Opcode:                 opcode,
		CPUName:                cpuName,
		PublicAssemblerName:    publicName,
		InternalAssemblerName:  internalName,
		DebugDisassemblerName:  debugName,
		StandaloneDisName:      standaloneName,
		CanonicalMnemonic:      mnemonic,
		FormatClass:            format,
		Assemblable:            true,
		PublicAssemblerForms:   []string{form},
		InternalAssemblerForms: []string{form},
		PublicOrigin:           0x1000,
		InternalOrigin:         0x1000,
	}
}
