#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

AROS_SRC_DIR="${AROS_SRC_DIR:-../AROS}"
AROS_BUILD_DIR="${AROS_BUILD_DIR:-$AROS_SRC_DIR/bin/ie-m68k}"
AROS_TREE="$AROS_BUILD_DIR/bin/ie-m68k/AROS"
AROS_ROM="${AROS_ROM:-./sdk/examples/prebuilt/aros-ie.rom}"

test -s "$AROS_TREE/S/Startup-Sequence"
test -s "$AROS_TREE/Libs/iffparse.library"
test -s "$AROS_TREE/Libs/kms.library"
test -s "$AROS_TREE/Libs/locale.library"
test -s "$AROS_TREE/C/IPrefs"
test -s "$AROS_TREE/System/FixFonts"
test -s "$AROS_TREE/Devs/Mountlist"
test -s "$AROS_TREE/Devs/DOSDrivers/DEBUG"
test -s "$AROS_TREE/Devs/DOSDrivers/PIPE"
test -s "$AROS_TREE/Devs/ahi.device"
test -s "$AROS_TREE/Devs/fdsk.device"
test -s "$AROS_TREE/Devs/Printers/PostScript"
test -s "$AROS_TREE/Devs/ramdrive.device"
test -s "$AROS_TREE/Libs/amigaguide.library"
test -s "$AROS_TREE/Libs/asyncio.library"
test -s "$AROS_TREE/Libs/commodities.library"
test -s "$AROS_TREE/Libs/camd.library"
test -s "$AROS_TREE/Libs/codesets.library"
test -s "$AROS_TREE/Libs/coolimages.library"
test -s "$AROS_TREE/System/Wanderer/Wanderer"
test -s "$AROS_TREE/Libs/asl.library"
test -s "$AROS_TREE/Libs/cybergraphics.library"
test -s "$AROS_TREE/Libs/datatypes.library"
test -s "$AROS_TREE/Libs/diskfont.library"
test -s "$AROS_TREE/Libs/expat.library"
test -s "$AROS_TREE/Libs/gadtools.library"
test -s "$AROS_TREE/Libs/identify.library"
test -s "$AROS_TREE/Libs/icon.library"
test -s "$AROS_TREE/Libs/jfif.library"
test -s "$AROS_TREE/Libs/lowlevel.library"
test -s "$AROS_TREE/Libs/lzma.library"
test -s "$AROS_TREE/Libs/mathffp.library"
test -s "$AROS_TREE/Libs/mathieeedoubbas.library"
test -s "$AROS_TREE/Libs/mathieeedoubtrans.library"
test -s "$AROS_TREE/Libs/mathieeesingbas.library"
test -s "$AROS_TREE/Libs/mathieeesingtrans.library"
test -s "$AROS_TREE/Libs/mathtrans.library"
test -s "$AROS_TREE/Libs/muimaster.library"
test -s "$AROS_TREE/Libs/muiscreen.library"
test -s "$AROS_TREE/Libs/popupmenu.library"
test -s "$AROS_TREE/Libs/png.library"
test -s "$AROS_TREE/Libs/reqtools.library"
test -s "$AROS_TREE/Libs/realtime.library"
test -s "$AROS_TREE/Libs/rexxsupport.library"
test -s "$AROS_TREE/Libs/tiff.library"
test -s "$AROS_TREE/Libs/utf8proc.library"
test -s "$AROS_TREE/Libs/version.library"
test -s "$AROS_TREE/Libs/z1.library"
test -s "$AROS_TREE/Libs/zstd.library"
test -s "$AROS_TREE/Libs/workbench.library"
test -s "$AROS_TREE/L/pipe-handler"
test -s "$AROS_TREE/L/port-handler"
test -s "$AROS_TREE/L/debug-handler"
test -s "$AROS_TREE/Rexxc/RX"
test -s "$AROS_TREE/Rexxc/RXLIB"
test -s "$AROS_TREE/Prefs/Env-Archive/SYS/Wanderer/backdrop.prefs"
test -s "$AROS_TREE/Classes/datatypes/jpeg.datatype"
test -d "$AROS_TREE/Devs/Monitors"
test -n "$(find "$AROS_TREE/Devs/Monitors" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)"
test -d "$AROS_TREE/Classes/datatypes"
test -n "$(find "$AROS_TREE/Classes/datatypes" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)"
test -d "$AROS_TREE/Classes/Gadgets"
test -n "$(find "$AROS_TREE/Classes/Gadgets" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)"
test -d "$AROS_TREE/Classes/Zune"
test -n "$(find "$AROS_TREE/Classes/Zune" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)"
test -d "$AROS_TREE/Libs/Zune"
test -n "$(find "$AROS_TREE/Libs/Zune" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)"
test -d "$AROS_TREE/Fonts"
test -s "$AROS_ROM"
