// Emit a Lua-readable mirror of the cases list so prm_runner.ies can
// `require("cases")` without a JSON parser in the sandbox. The mirror is
// strictly informational for the Lua runner — the orchestrator phases
// continue to read cases.json.

package main

import (
	"fmt"
	"os"
	"strings"
)

func writeCasesLua(cases []Case, path string) error {
	var sb strings.Builder
	sb.WriteString("-- Auto-generated by prm-extract. Do not edit by hand.\n")
	sb.WriteString("return {\n")
	sb.WriteString("  cases = {\n")
	for _, c := range cases {
		sb.WriteString("    {")
		sb.WriteString(fmt.Sprintf("id=%q,", c.ID))
		sb.WriteString(fmt.Sprintf("source=%q,", c.Source))
		sb.WriteString(fmt.Sprintf("fence_start_line=%d,", c.FenceStartLine))
		sb.WriteString(fmt.Sprintf("kind=%q,", c.Kind))
		sb.WriteString(fmt.Sprintf("status=%q,", c.Status))
		if c.SkipReason != "" {
			sb.WriteString(fmt.Sprintf("skip_reason=%q,", c.SkipReason))
		}
		if c.Mode != "" {
			sb.WriteString(fmt.Sprintf("mode=%q,", c.Mode))
		}
		if c.CPU != "" {
			sb.WriteString(fmt.Sprintf("cpu=%q,", c.CPU))
		}
		if len(c.BasicSteps) > 0 {
			sb.WriteString("basic_steps={")
			for _, s := range c.BasicSteps {
				sb.WriteString("{")
				sb.WriteString(fmt.Sprintf("input=%s,", luaQuote(s.Input)))
				sb.WriteString("expected={")
				for _, e := range s.Expected {
					sb.WriteString(luaQuote(e))
					sb.WriteString(",")
				}
				sb.WriteString("},")
				if s.ExpectsOutput {
					sb.WriteString("expects_output=true,")
				}
				if s.Loose {
					sb.WriteString("loose=true,")
				}
				sb.WriteString("},")
			}
			sb.WriteString("},")
		}
		if c.APILint != nil {
			sb.WriteString(fmt.Sprintf("api_lint={status=%q,", c.APILint.Status))
			if len(c.APILint.Unknown) > 0 {
				sb.WriteString("unknown={")
				for _, u := range c.APILint.Unknown {
					sb.WriteString(fmt.Sprintf("%q,", u))
				}
				sb.WriteString("},")
			}
			sb.WriteString("},")
		}
		sb.WriteString("},\n")
	}
	sb.WriteString("  },\n")
	sb.WriteString("}\n")
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}
