// IE Monitor (iemon) phase orchestration.
//
// For each iemon Case, the extract phase has serialized the step list into
// the case JSON. The orchestrator generates a per-case Lua child wrapper
// at `build/<id>.iemon.ies` that:
//   - opens the monitor (dbg.open) which freezes the park-loop stub,
//   - dispatches each step through dbg.command_output / dbg.continue,
//   - prints `STEP n CMD: ...` and (for strict steps) the captured rows,
//   - prints BLOCKS_REST / BLOCKED markers when a `blocks_rest:true` skip
//     is reached so the orchestrator can clearly attribute downstream
//     fails to the upstream skip.
//
// Per-case child launch:
//
//	./bin/IntuitionEngine <cpu-flag> -script-owned-term \
//	    -script sdk/scripts/prm-runner/build/<id>.iemon.ies \
//	    sdk/scripts/prm-runner/stubs/<cpu>.bin

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

var cpuFlagMap = map[string]string{
	"ie64": "-ie64",
	"ie32": "-ie32",
	"6502": "-m6502",
	"z80":  "-z80",
	"m68k": "-m68k",
	"x86":  "-x86",
}

func writeIemonWrappers(cases []Case, build, root string) error {
	for _, c := range cases {
		if c.Kind != KindIemon || c.Status != StatusReady {
			continue
		}
		wrap := buildIemonWrapper(c)
		path := filepath.Join(build, c.ID+".iemon.ies")
		if err := os.WriteFile(path, []byte(wrap), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// buildIemonWrapper emits the Lua child driver for one iemon case.
//
// The wrapper inlines prm_lib.flatten + a small step-dispatch helper, then
// serializes the step list as a Lua table literal so the wrapper does not
// need to read cases.json from inside the sandbox.
func buildIemonWrapper(c Case) string {
	var sb strings.Builder
	sb.WriteString(`-- Auto-generated by prm-extract. Do not edit by hand.
local RED = 0xFF5555FF
local function flatten(rows)
  if type(rows) ~= "table" then return tostring(rows) end
  local out = {}
  for _, r in ipairs(rows) do out[#out+1] = r.text or "" end
  return table.concat(out, "\n")
end
local function check_error_rows(i, rows)
  if type(rows) ~= "table" then return end
  for _, r in ipairs(rows) do
    if r.color == RED then error("STEP "..i..": monitor error: "..(r.text or "")) end
    local t = r.text or ""
    if t:sub(1,1) == "?" or t:find("^error:") or t:find("^unknown command") then
      error("STEP "..i..": monitor error: "..t)
    end
  end
end
local function wait_halt(i, label, timeout_ms)
  -- dbg.continue exits the monitor and resumes the CPU, but
  -- cpu.is_running() can read false momentarily before the CPU
  -- scheduler picks up the Resume (or after a tiny program has
  -- already raced through its instructions and hit the breakpoint
  -- before our first poll). A naive halt-poll therefore exits
  -- immediately and the next monitor command re-freezes the CPU
  -- before its writes have landed. Wait briefly for is_running to
  -- become true first, then poll for it to go false; if it never
  -- goes true the program was already done, so fall through to
  -- the halt check anyway.
  local start_deadline = sys.time_ms() + 100
  while not cpu.is_running() and sys.time_ms() < start_deadline do sys.wait_ms(2) end
  local deadline = sys.time_ms() + timeout_ms
  while cpu.is_running() and sys.time_ms() < deadline do sys.wait_ms(10) end
  if cpu.is_running() then error("STEP "..i..": "..label.." did not halt within "..timeout_ms.."ms") end
end
local function run_step(i, step)
  if step.kind == "skip" then
    sys.print("STEP "..i.." SKIP: "..(step.skip_reason or "unspecified"))
    if step.blocks_rest then
      sys.print("STEP "..i.." BLOCKS_REST: subsequent steps depend on skipped state-changing command")
      return "blocked"
    end
    return "skip"
  end
  sys.print("STEP "..i.." CMD: "..step.cmd)
  if step.kind == "go" then
    dbg.continue(true)
    wait_halt(i, "g", step.timeout_ms or 5000)
  elseif step.kind == "step" or step.kind == "backstep" then
    local rows = dbg.command_output(step.cmd)
    check_error_rows(i, rows)
    if step.expected_mode == "strict" then sys.print(flatten(rows)) end
  else
    local rows = dbg.command_output(step.cmd)
    check_error_rows(i, rows)
    if step.expected_mode == "strict" then sys.print(flatten(rows)) end
  end
  return "ok"
end
local steps = `)
	sb.WriteString(luaStepTable(c.IemonSteps))
	sb.WriteString(`
sys.print("=== PRM_BEGIN ===")
local ok, err = pcall(function()
  dbg.open()
  for i, step in ipairs(steps) do
    local r = run_step(i, step)
    if r == "blocked" then
      for j = i+1, #steps do
        sys.print("STEP "..j.." BLOCKED: prior skip blocks downstream")
      end
      break
    end
  end
  dbg.close()
end)
if not ok then sys.print("PRM_IEMON_ERROR: " .. tostring(err)) end
sys.print("=== PRM_END ===")
sys.exit(ok and 0 or 1)
`)
	return sb.String()
}

// luaStepTable emits a Lua table literal for the step list.
func luaStepTable(steps []IemonStep) string {
	var sb strings.Builder
	sb.WriteString("{\n")
	for _, s := range steps {
		sb.WriteString("  {")
		sb.WriteString(fmt.Sprintf("cmd=%s,", luaQuote(s.Cmd)))
		sb.WriteString(fmt.Sprintf("kind=%q,", s.Kind))
		sb.WriteString(fmt.Sprintf("expected_mode=%q,", s.ExpectedMode))
		if s.TimeoutMS > 0 {
			sb.WriteString(fmt.Sprintf("timeout_ms=%d,", s.TimeoutMS))
		}
		if s.SkipReason != "" {
			sb.WriteString(fmt.Sprintf("skip_reason=%q,", s.SkipReason))
		}
		if s.BlocksRest {
			sb.WriteString("blocks_rest=true,")
		}
		sb.WriteString("},\n")
	}
	sb.WriteString("}")
	return sb.String()
}

// luaQuote returns a Lua long-bracket string so embedded quotes/newlines
// don't need escaping. We pick a bracket level not present in the input.
func luaQuote(s string) string {
	for lvl := 0; lvl < 20; lvl++ {
		eq := strings.Repeat("=", lvl)
		end := "]" + eq + "]"
		if !strings.Contains(s, end) {
			return "[" + eq + "[" + s + end
		}
	}
	// Fallback: pure escape.
	b, _ := json.Marshal(s)
	return string(b)
}

func runIemonPhase(in, build, appendTo, root, binary string) {
	cases, err := readCases(in)
	if err != nil {
		die(err)
	}
	var report Report
	if appendTo != "" {
		if existing, err := readReport(appendTo); err == nil {
			report = *existing
		}
	}
	failures := 0
	for _, c := range cases.Cases {
		if c.Kind != KindIemon {
			continue
		}
		if c.Status == StatusSkip {
			report.Cases = append(report.Cases, ReportCase{
				ID:             c.ID,
				Source:         c.Source,
				FenceStartLine: c.FenceStartLine,
				Kind:           c.Kind,
				CPU:            c.CPU,
				Status:         RStatusSkip,
				SkipReason:     c.SkipReason,
			})
			continue
		}
		rc := runIemonCase(c, build, root, binary)
		if isCaseFailure(rc.Status) {
			failures++
		}
		report.Cases = append(report.Cases, rc)
	}
	if appendTo != "" {
		if err := writeReport(appendTo, &report); err != nil {
			die(err)
		}
	}
	if failures > 0 {
		os.Exit(1)
	}
}

func runIemonCase(c Case, build, root, binary string) ReportCase {
	rc := ReportCase{
		ID:             c.ID,
		Source:         c.Source,
		FenceStartLine: c.FenceStartLine,
		Kind:           c.Kind,
		CPU:            c.CPU,
	}
	flag, ok := cpuFlagMap[c.CPU]
	if !ok {
		rc.Status = RStatusError
		rc.Error = "unknown cpu " + c.CPU
		return rc
	}
	wrapperRel := filepath.ToSlash(filepath.Join(build, c.ID+".iemon.ies"))
	stubRel := filepath.ToSlash(filepath.Join("sdk", "scripts", "prm-runner", "stubs", c.CPU+".bin"))

	// Per-case timeout: sum of per-step timeouts + 2s slack, min 10s.
	totalMS := 2000
	for _, s := range c.IemonSteps {
		if s.TimeoutMS > 0 {
			totalMS += s.TimeoutMS
		} else {
			totalMS += defaultIemonTimeoutMS
		}
	}
	if totalMS < 10000 {
		totalMS = 10000
	}
	timeout := time.Duration(totalMS) * time.Millisecond

	cmd := exec.Command(binary, flag, "-script-owned-term", "-script", wrapperRel, stubRel)
	cmd.Dir = root
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if err := cmd.Start(); err != nil {
		rc.Status = RStatusError
		rc.Error = "start: " + err.Error()
		return rc
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	var waitErr error
	select {
	case waitErr = <-done:
	case <-time.After(timeout):
		_ = cmd.Process.Kill()
		<-done
		rc.Status = RStatusError
		rc.Error = "case timeout"
		return rc
	}

	body, ok := sliceBetween(stdout.String(), prmBegin, prmEnd)
	if !ok {
		rc.Status = RStatusError
		rc.Error = "sentinels missing; stderr=" + truncate(stderr.String(), 400)
		return rc
	}
	steps, err := parseIemonChildOutput(body, c.IemonSteps)
	if err != nil {
		rc.Status = RStatusError
		rc.Error = err.Error()
		rc.Steps = steps
		return rc
	}
	rc.Steps = steps
	rc.Status = aggregateStatus(steps)
	// A wrapper that printed sentinels but exited non-zero is signaling
	// either an in-band PRM_IEMON_ERROR (caught by pcall and printed
	// before the end sentinel) or a crash. Either way, the case must not
	// report PASS even if all expected_mode:"ignore" steps "diff" clean.
	if waitErr != nil {
		if rc.Status != RStatusFail {
			rc.Status = RStatusError
		}
		if ee, ok := waitErr.(*exec.ExitError); ok {
			rc.Error = fmt.Sprintf("child exited with status %d", ee.ExitCode())
		} else {
			rc.Error = "child wait: " + waitErr.Error()
		}
	}
	return rc
}

// parseIemonChildOutput walks the captured between-sentinels text and
// pairs `STEP n …` segments with the original IemonSteps for diffing.
func parseIemonChildOutput(body string, steps []IemonStep) ([]ReportStep, error) {
	lines := strings.Split(body, "\n")
	type seg struct {
		idx     int
		kind    string // CMD | SKIP | BLOCKED | BLOCKS_REST
		reason  string
		payload []string
	}
	var segs []seg
	var cur *seg
	for _, ln := range lines {
		if strings.HasPrefix(ln, "STEP ") {
			rest := strings.TrimPrefix(ln, "STEP ")
			sp := strings.IndexByte(rest, ' ')
			if sp < 0 {
				continue
			}
			idx := 0
			fmt.Sscanf(rest[:sp], "%d", &idx)
			marker := rest[sp+1:]
			s := seg{idx: idx}
			switch {
			case strings.HasPrefix(marker, "CMD:"):
				s.kind = "CMD"
			case strings.HasPrefix(marker, "SKIP:"):
				s.kind = "SKIP"
				s.reason = strings.TrimSpace(strings.TrimPrefix(marker, "SKIP:"))
			case strings.HasPrefix(marker, "BLOCKED:"):
				s.kind = "BLOCKED"
				s.reason = strings.TrimSpace(strings.TrimPrefix(marker, "BLOCKED:"))
			case strings.HasPrefix(marker, "BLOCKS_REST:"):
				// attach to current; not its own segment
				if cur != nil {
					cur.payload = append(cur.payload, "")
				}
				continue
			default:
				continue
			}
			if cur != nil {
				segs = append(segs, *cur)
			}
			cur = &s
			continue
		}
		if cur != nil {
			cur.payload = append(cur.payload, ln)
		}
	}
	if cur != nil {
		segs = append(segs, *cur)
	}

	// Build report steps, indexed by original step number.
	rs := make([]ReportStep, len(steps))
	for i, s := range steps {
		rs[i] = ReportStep{
			Cmd:      s.Cmd,
			Kind:     s.Kind,
			Expected: splitLines(s.Expected),
		}
	}
	for _, sg := range segs {
		if sg.idx < 1 || sg.idx > len(steps) {
			continue
		}
		s := steps[sg.idx-1]
		r := &rs[sg.idx-1]
		switch sg.kind {
		case "CMD":
			r.Actual = trimTrailingBlanks(sg.payload)
			r.Status = diffStatus(s, splitLines(s.Expected), r.Actual)
		case "SKIP":
			r.Status = RStatusSkip
			r.SkipReason = sg.reason
		case "BLOCKED":
			r.Status = RStatusBlocked
			r.SkipReason = sg.reason
		}
	}
	// Steps with no captured segment (child crashed mid-case) → ERROR.
	for i := range rs {
		if rs[i].Status == "" {
			rs[i].Status = RStatusError
		}
	}
	return rs, nil
}

func splitLines(s string) []string {
	if s == "" {
		return nil
	}
	return strings.Split(s, "\n")
}

func trimTrailingBlanks(xs []string) []string {
	for len(xs) > 0 && strings.TrimSpace(xs[len(xs)-1]) == "" {
		xs = xs[:len(xs)-1]
	}
	return xs
}

func diffStatus(s IemonStep, expected, actual []string) string {
	if s.ExpectedMode == ExpectedIgnore {
		// We screen errors row-side in the wrapper; reaching here means no
		// red row was observed, so the step passes.
		return RStatusPass
	}
	if linesEqual(expected, actual) {
		return RStatusPass
	}
	return RStatusFail
}

func linesEqual(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func aggregateStatus(steps []ReportStep) string {
	for _, s := range steps {
		if s.Status == RStatusFail || s.Status == RStatusError {
			return RStatusFail
		}
	}
	return RStatusPass
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
