// IES runnable phase orchestration.
//
// For each `Mode=="runnable"` case, the extract phase has written a
// wrapped `build/<id>.ies` snippet that prints `=== PRM_BEGIN ===` /
// `=== PRM_END ===` sentinels around the snippet body and intercepts
// `sys.exit`/`sys.quit` so the orchestrator can extract stdout between
// the sentinels for diffing.
//
// This phase launches the child:
//
//	./bin/IntuitionEngine -basic -term -script-owned-term \
//	    -script sdk/scripts/prm-runner/build/<id>.ies
//
// captures stdout, slices between the sentinels, diffs against
// ExpectedStdout, and appends one ReportCase per IES case to report.json.
//
// IES lint-only cases (Mode=="lint") are emitted by the BASIC runner via
// the Lua side, so this phase only runs the `runnable` subset.

package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	prmBegin = "=== PRM_BEGIN ==="
	prmEnd   = "=== PRM_END ==="
)

// writeIESWrappers emits one `<id>.ies` per runnable IES case.
func writeIESWrappers(cases []Case, build string) error {
	for _, c := range cases {
		if c.Kind != KindIES || c.Mode != IESModeRunnable {
			continue
		}
		body, err := loadFenceBody(c)
		if err != nil {
			return err
		}
		wrapped := wrapIESSnippet(body)
		path := filepath.Join(build, c.ID+".ies")
		if err := os.WriteFile(path, []byte(wrapped), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

// loadFenceBody re-reads the source markdown to recover the verbatim
// snippet text for a given case. The extract phase strips a lot in
// classification; for runnable IES we want the raw body.
func loadFenceBody(c Case) (string, error) {
	// Read source markdown, walk to the fence at c.FenceStartLine, return
	// its body. We re-parse here rather than carry the body around in
	// every case to keep cases.json small.
	data, err := os.ReadFile(c.Source)
	if err != nil {
		return "", err
	}
	lines := strings.Split(string(data), "\n")
	if c.FenceStartLine <= 0 || c.FenceStartLine > len(lines) {
		return "", fmt.Errorf("%s: fence at line %d out of range", c.Source, c.FenceStartLine)
	}
	start := c.FenceStartLine // 1-based: this is the opening ``` line.
	var body []string
	for i := start; i < len(lines); i++ {
		if strings.TrimRight(lines[i], " \t") == "```" {
			return strings.Join(body, "\n"), nil
		}
		body = append(body, lines[i])
	}
	return "", fmt.Errorf("%s: unterminated fence at line %d", c.Source, c.FenceStartLine)
}

func wrapIESSnippet(snippet string) string {
	var sb strings.Builder
	sb.WriteString(`-- Auto-generated by prm-extract. Do not edit by hand.
sys.print("` + prmBegin + `")
local _real_exit = sys.exit
local function _intercept(code) error({__prm_exit = code or 0}) end
sys.exit = _intercept
sys.quit = _intercept
local _exit_code = 0
local ok, err = pcall(function()
`)
	sb.WriteString(snippet)
	sb.WriteString(`
end)
if not ok then
  if type(err) == "table" and err.__prm_exit ~= nil then
    _exit_code = err.__prm_exit
  else
    sys.print("PRM_IES_ERROR: " .. tostring(err))
    _exit_code = 1
  end
end
sys.print("` + prmEnd + `")
_real_exit(_exit_code)
`)
	return sb.String()
}

func runIESPhase(in, build, appendTo, root, binary string) {
	cases, err := readCases(in)
	if err != nil {
		die(err)
	}
	var report Report
	if appendTo != "" {
		if existing, err := readReport(appendTo); err == nil {
			report = *existing
		}
	}
	failures := 0
	for _, c := range cases.Cases {
		if c.Kind != KindIES || c.Mode != IESModeRunnable {
			continue
		}
		rc := runIESCase(c, build, root, binary)
		if isCaseFailure(rc.Status) {
			failures++
		}
		report.Cases = append(report.Cases, rc)
	}
	if appendTo != "" {
		if err := writeReport(appendTo, &report); err != nil {
			die(err)
		}
	}
	// Phase exits non-zero when any IES case it ran reported FAIL/ERROR.
	// The orchestrator script's final aggregation then fails the run.
	if failures > 0 {
		os.Exit(1)
	}
}

// isCaseFailure is true for any status that should fail the orchestrator.
// SKIP and LINT_PASS are not failures; only FAIL/ERROR/LINT_FAIL are.
func isCaseFailure(status string) bool {
	switch status {
	case RStatusFail, RStatusError, RStatusLintFail:
		return true
	}
	return false
}

func runIESCase(c Case, build, root, binary string) ReportCase {
	rc := ReportCase{
		ID:             c.ID,
		Source:         c.Source,
		FenceStartLine: c.FenceStartLine,
		Kind:           c.Kind,
	}
	wrapperRel := filepath.ToSlash(filepath.Join(build, c.ID+".ies"))
	timeout := time.Duration(c.IESTimeoutS) * time.Second
	if timeout == 0 {
		timeout = 5 * time.Second
	}
	cmd := exec.Command(binary, "-basic", "-term", "-script-owned-term", "-script", wrapperRel)
	cmd.Dir = root
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	done := make(chan error, 1)
	if err := cmd.Start(); err != nil {
		rc.Status = RStatusError
		rc.Error = fmt.Sprintf("start: %v", err)
		return rc
	}
	go func() { done <- cmd.Wait() }()
	var waitErr error
	select {
	case waitErr = <-done:
	case <-time.After(timeout):
		_ = cmd.Process.Kill()
		<-done
		rc.Status = RStatusError
		rc.Error = "timeout"
		return rc
	}

	out := stdout.String()
	body, ok := sliceBetween(out, prmBegin, prmEnd)
	if !ok {
		rc.Status = RStatusError
		rc.Error = "sentinels missing"
		return rc
	}
	expected := strings.TrimRight(c.ExpectedStdout, "\n")
	actual := strings.TrimRight(body, "\n")
	step := ReportStep{
		Expected: strings.Split(expected, "\n"),
		Actual:   strings.Split(actual, "\n"),
	}
	if expected == actual {
		step.Status = RStatusPass
		rc.Status = RStatusPass
	} else {
		step.Status = RStatusFail
		rc.Status = RStatusFail
	}
	rc.Steps = []ReportStep{step}
	// A snippet that calls sys.exit(N) with N != 0 (or that errors out
	// inside the pcall such that the wrapper's _real_exit gets a non-zero
	// code) must not be reported as PASS even when stdout matched. The
	// wrapper prints the error inside sentinels so the diff records it,
	// but the exit code is the snippet's only way to signal "I matched
	// my expected output but I am still failing on purpose."
	if waitErr != nil {
		if rc.Status == RStatusPass {
			rc.Status = RStatusFail
			step.Status = RStatusFail
			rc.Steps = []ReportStep{step}
		}
		if ee, ok := waitErr.(*exec.ExitError); ok {
			rc.Error = fmt.Sprintf("child exited with status %d", ee.ExitCode())
		} else {
			rc.Error = "child wait: " + waitErr.Error()
		}
	}
	return rc
}

func sliceBetween(s, start, end string) (string, bool) {
	i := strings.Index(s, start)
	if i < 0 {
		return "", false
	}
	rest := s[i+len(start):]
	j := strings.Index(rest, end)
	if j < 0 {
		return "", false
	}
	out := rest[:j]
	out = strings.TrimPrefix(out, "\n")
	out = strings.TrimSuffix(out, "\n")
	return out, true
}

func readCases(path string) (*CasesFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var c CasesFile
	if err := json.Unmarshal(data, &c); err != nil {
		return nil, err
	}
	return &c, nil
}

func readReport(path string) (*Report, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return &Report{}, nil
		}
		return nil, err
	}
	var r Report
	if err := json.Unmarshal(data, &r); err != nil {
		return nil, err
	}
	return &r, nil
}

func writeReport(path string, r *Report) error {
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}
