// Command gen_aot_consttab generates the AOT private assembler's constant table
// from the equ definitions in ie64.inc. The in-guest private assembler resolves
// operands like "#ST_ERROR_FLAG" or "la r1, BASIC_STATE" against this table, so
// helper source can be bundled and assembled at the link base without the
// assembler needing include/equ support.
//
// Each entry is [name pointer, value]. The value is emitted as the equ symbol
// itself, so ie64asm resolves it when the EhBASIC image is built. The output is
// committed (sdk/include/aot_consttab.inc) for reproducible builds.
//
// Usage: go run ./tools/gen_aot_consttab [-in ie64.inc] [-out aot_consttab.inc]
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// equ definitions look like:  NAME       equ 0x1234   ; comment
var equRe = regexp.MustCompile(`^\s*([A-Za-z_][A-Za-z0-9_]*)\s+equ\s`)

// includeConsttabPrefixes is the namespace allowlist the embedded AOT constant table
// keeps. The table is consulted ONLY by the in-guest private assembler to resolve a
// named constant that appears as an operand in bundled helper SOURCE assembled at
// compile time (aot_const_lookup, the fallback after program-label lookup).
//
// BASIC hardware access does NOT use this table: hardware statements (SID PLAY, POKE,
// SCREEN, ...) are lowered by the transpiler to numeric immediates resolved against
// ie64.inc at main-image assembly time, and the runtime is bundled as machine code
// (the COMPILE runtime blob), not assembled in-guest. So only BASIC/system/assembler
// constants could ever be referenced by bundled source; the chip peripheral register
// namespaces (VOODOO/GTIA/TED/SID/BLT/ANTIC/VGA/ULA/POKEY/FLEX/audio chips/...) never
// are. Those equs remain in ie64.inc and stay fully available to BASIC; they are
// simply not pre-loaded in the in-guest symbol table.
//
// Generating all ~1000 ie64.inc equs (18 KiB) left the interpreter image within ~40
// bytes of the BASIC line buffer at 0x021000 (crossing it corrupts RUN AOT).
// Restricting the table to these namespaces keeps it ~4 KiB and clear of that wall.
// An empty table passes the full AOT suite today, so this allowlist is conservative.
// If a future bundled helper source references a dropped constant, add its namespace
// here (the in-guest assembler fails loudly on an unresolved symbol).
var includeConsttabPrefixes = []string{
	"AOT_", "ST_", "BASIC_", "TERM_", "FILE_", "ERR_", "EXEC_", "IE_",
	"VECTOR_", "PROGRAM", "STACK_", "SYS_", "SYSINFO_", "CR_", "IO_",
	"MEM_", "FP_", "TK_", "MODE_", "MEDIA_",
}

// excludeFromConsttab drops the standalone runtime blob constants (resolved at
// main-image assembly time, never by name in-guest) and every constant outside the
// BASIC/system/assembler namespaces above.
func excludeFromConsttab(name string) bool {
	if name == "AOT_RT_BASE" || name == "AOT_RT_LIMIT" || strings.HasPrefix(name, "RT_") {
		return true
	}
	for _, p := range includeConsttabPrefixes {
		if strings.HasPrefix(name, p) {
			return false
		}
	}
	return true
}

func main() {
	in := flag.String("in", "sdk/include/ie64.inc", "input .inc file with equ definitions")
	out := flag.String("out", "sdk/include/aot_consttab.inc", "output asm include")
	flag.Parse()

	f, err := os.Open(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen_aot_consttab:", err)
		os.Exit(1)
	}
	defer f.Close()

	var names []string
	seen := map[string]bool{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		m := equRe.FindStringSubmatch(sc.Text())
		if m == nil {
			continue
		}
		name := m[1]
		if seen[name] {
			continue // first definition wins; ie64asm rejects real duplicates
		}
		if excludeFromConsttab(name) {
			continue
		}
		seen[name] = true
		names = append(names, name)
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "gen_aot_consttab:", err)
		os.Exit(1)
	}

	// Compact, unaligned record format to keep the table small (it lives in the
	// low image region below the BASIC state block): each record is
	//   [name length : 1][name bytes][value : 4 little-endian]
	// terminated by a zero length byte. Values fit in 32 bits and are emitted as
	// the equ symbol so ie64asm resolves them when the image is built.
	var b strings.Builder
	b.WriteString("; Auto-generated by tools/gen_aot_consttab from " + *in + ". Do not edit.\n")
	b.WriteString("; AOT private-assembler constant table. Each record: [len:1][name][value:4 LE],\n")
	b.WriteString("; terminated by a zero length byte. Run `make gen-aot-consttab` to regenerate.\n\n")
	b.WriteString("aot_consttab:\n")
	for _, n := range names {
		fmt.Fprintf(&b, "    dc.b %d, \"%s\"\n    dc.l %s\n", len(n), n, n)
	}
	b.WriteString("    dc.b 0\n")

	if err := os.WriteFile(*out, []byte(b.String()), 0644); err != nil {
		fmt.Fprintln(os.Stderr, "gen_aot_consttab:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen_aot_consttab: wrote %d constants to %s\n", len(names), *out)
}
